// SPDX-FileCopyrightText: 2026 James L. Burns and The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// RenderBusinessCasePDF is the bespoke renderer for the Business Case.
// The document is a hybrid: prose-heavy in places (problem, solution,
// recommendation), table-heavy in others (alternatives with pros/cons,
// benefits vs risks side-by-side). Layout follows pattern 4 (hybrid
// card list) from the AGENT.md taxonomy.
//
// Layout:
//
//	Title bar:            Project name + "Business Case"
//	Section: Problem / Opportunity      (FieldText)
//	Section: Proposed Solution          (FieldText, accent-bordered)
//	Section: Alternatives Considered    (one card per alternative,
//	                                     two-column pros / cons)
//	Section: Cost & ROI summary         (KV pairs)
//	Section: Benefits vs Risks          (two-column bulleted lists)
//	Section: Recommendation             (accent-boxed)
//	Footer:                             generation timestamp
func RenderBusinessCasePDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("P")
	pdf.SetMargins(20, 18, 20)
	pdf.SetAutoPageBreak(true, 18)
	pdf.SetTitle("Business Case", true)
	pdf.AddPage()

	// Title block
	pdf.SetFont("Helvetica", "B", 22)
	pdf.Cell(0, 12, getString(content, "project_name", projectName))
	pdf.Ln(13)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "Business Case")
	pdf.Ln(8)
	pdf.SetTextColor(0, 0, 0)

	bcSection(pdf, "Problem / Opportunity", getString(content, "problem_statement", ""))
	bcAccentSection(pdf, "Proposed Solution", getString(content, "proposed_solution", ""))

	if alts := getObjectSlice(content, "alternatives"); len(alts) > 0 {
		bcHeading(pdf, "Alternatives Considered")
		for _, a := range alts {
			drawBCAlternative(pdf,
				getStringBC(a, "name"),
				getStringBC(a, "pros"),
				getStringBC(a, "cons"))
		}
	}

	// Cost + ROI summary
	cost, _ := content["costs_summary"].(float64)
	roi := getString(content, "roi", "")
	if cost != 0 || roi != "" {
		bcHeading(pdf, "Cost & ROI Summary")
		if cost != 0 {
			pdf.SetFont("Helvetica", "B", 10)
			pdf.CellFormat(50, 6, "Cost summary:", "", 0, "L", false, 0, "")
			pdf.SetFont("Helvetica", "", 10)
			pdf.CellFormat(0, 6, "USD "+formatMoney(cost), "", 0, "L", false, 0, "")
			pdf.Ln(-1)
		}
		if roi != "" {
			pdf.SetFont("Helvetica", "B", 10)
			pdf.CellFormat(50, 6, "ROI / Payback:", "", 0, "L", false, 0, "")
			pdf.SetFont("Helvetica", "", 10)
			pdf.MultiCell(0, 6, roi, "", "L", false)
		}
		pdf.Ln(2)
	}

	// Benefits vs Risks — two-column layout
	benefits := getStringSlice(content, "benefits")
	risks := getStringSlice(content, "risks")
	if len(benefits) > 0 || len(risks) > 0 {
		bcHeading(pdf, "Benefits vs Risks")
		drawBCTwoColumn(pdf, "Expected Benefits", benefits, "Key Risks", risks)
	}

	// Recommendation
	if rec := getString(content, "recommendation", ""); rec != "" {
		bcHeading(pdf, "Recommendation")
		drawBCRecommendation(pdf, rec)
	}

	DrawCompactSignatureBox(pdf, projectName, time.Now().Format("2006-01-02"))

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func bcHeading(pdf *gofpdf.Fpdf, text string) {
	pdf.Ln(3)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(0, 80, 130)
	pdf.Cell(0, 7, text)
	pdf.Ln(7)
	pdf.SetTextColor(0, 0, 0)
}

func bcSection(pdf *gofpdf.Fpdf, heading, body string) {
	if body == "" {
		return
	}
	bcHeading(pdf, heading)
	pdf.SetFont("Helvetica", "", 10)
	pdf.MultiCell(0, 5, body, "", "L", false)
	pdf.Ln(2)
}

// bcAccentSection renders body text with a teal left rule to visually
// elevate it. Used for the Proposed Solution — the centrepiece of the
// document.
func bcAccentSection(pdf *gofpdf.Fpdf, heading, body string) {
	if body == "" {
		return
	}
	bcHeading(pdf, heading)
	pdf.SetFont("Helvetica", "", 10)
	startY := pdf.GetY()
	pdf.SetX(24)
	pdf.MultiCell(166, 5, body, "", "L", false)
	endY := pdf.GetY()

	pdf.SetDrawColor(14, 116, 144)
	pdf.SetLineWidth(1.0)
	pdf.Line(20, startY, 20, endY)
	pdf.SetLineWidth(0.2)
	pdf.SetDrawColor(0, 0, 0)
	pdf.Ln(2)
}

// drawBCAlternative renders one alternative as a bordered card with a
// header (the alternative's name) and two columns underneath (pros |
// cons).
func drawBCAlternative(pdf *gofpdf.Fpdf, name, pros, cons string) {
	if name == "" && pros == "" && cons == "" {
		return
	}
	startY := pdf.GetY()
	cardW := 170.0
	headerH := 7.0

	// Header bar
	pdf.SetFillColor(243, 244, 246)
	pdf.SetDrawColor(209, 213, 219)
	pdf.Rect(20, startY, cardW, headerH, "FD")
	pdf.SetXY(22, startY+1.5)
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetTextColor(17, 24, 39)
	pdf.CellFormat(cardW-4, 4, name, "", 0, "L", false, 0, "")

	// Pros column (left)
	colY := startY + headerH + 1
	colW := cardW / 2

	prosY := drawBCColumn(pdf, 20, colY, colW, "Pros", pros, 21, 128, 61)
	consY := drawBCColumn(pdf, 20+colW, colY, colW, "Cons", cons, 185, 28, 28)

	// Outer card border
	endY := prosY
	if consY > endY {
		endY = consY
	}
	endY += 2
	pdf.SetDrawColor(209, 213, 219)
	pdf.Rect(20, startY, cardW, endY-startY, "D")
	// Vertical divider between Pros and Cons
	pdf.Line(20+colW, startY+headerH, 20+colW, endY)

	pdf.SetXY(20, endY+2)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetDrawColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
}

// drawBCColumn writes a small heading + body inside one card column
// and returns the ending Y so the caller can compute the outer card
// height.
func drawBCColumn(pdf *gofpdf.Fpdf, x, y, w float64, title, body string, tr, tg, tb int) float64 {
	pdf.SetXY(x+2, y)
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetTextColor(tr, tg, tb)
	pdf.CellFormat(w-4, 4, title, "", 0, "L", false, 0, "")
	pdf.SetXY(x+2, y+5)
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(17, 24, 39)
	if body == "" {
		body = "—"
	}
	pdf.MultiCell(w-4, 4.5, body, "", "L", false)
	return pdf.GetY()
}

// drawBCTwoColumn renders two bulleted lists side-by-side under their
// own coloured headings. Used for Benefits vs Risks.
func drawBCTwoColumn(pdf *gofpdf.Fpdf, leftTitle string, left []string, rightTitle string, right []string) {
	startY := pdf.GetY()
	colW := 85.0

	// Left column
	pdf.SetXY(20, startY)
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetTextColor(21, 128, 61)
	pdf.CellFormat(colW, 5, leftTitle, "", 0, "L", false, 0, "")

	// Right column header
	pdf.SetXY(20+colW, startY)
	pdf.SetTextColor(185, 28, 28)
	pdf.CellFormat(colW, 5, rightTitle, "", 0, "L", false, 0, "")
	pdf.Ln(6)

	bodyTop := pdf.GetY()
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFont("Helvetica", "", 9)

	// Left bullets
	pdf.SetXY(20, bodyTop)
	for _, item := range left {
		pdf.SetX(20)
		pdf.Cell(4, 5, "\xe2\x80\xa2")
		pdf.MultiCell(colW-5, 5, item, "", "L", false)
	}
	leftEnd := pdf.GetY()

	// Right bullets
	pdf.SetXY(20+colW, bodyTop)
	for _, item := range right {
		pdf.SetX(20 + colW)
		pdf.Cell(4, 5, "\xe2\x80\xa2")
		pdf.MultiCell(colW-5, 5, item, "", "L", false)
	}
	rightEnd := pdf.GetY()

	endY := leftEnd
	if rightEnd > endY {
		endY = rightEnd
	}
	pdf.SetXY(20, endY+2)
}

// drawBCRecommendation renders the recommendation as an accent-boxed
// callout so the executive reader's eye lands on it.
func drawBCRecommendation(pdf *gofpdf.Fpdf, body string) {
	startY := pdf.GetY()
	pdf.SetFillColor(239, 246, 255)
	pdf.SetDrawColor(59, 130, 246)
	pdf.SetX(20)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(30, 58, 138)

	// Inset the text from the box edges.
	pdf.SetXY(24, startY+2)
	pdf.MultiCell(162, 5, body, "", "L", false)
	endY := pdf.GetY()

	// Draw the box AFTER the text so we know the height.
	pdf.SetLineWidth(0.5)
	pdf.Rect(20, startY, 170, endY-startY+3, "D")
	pdf.SetLineWidth(0.2)

	pdf.SetXY(20, endY+5)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetDrawColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
}

func getStringBC(m map[string]interface{}, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}
