// SPDX-FileCopyrightText: 2026 James L. Burns and The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"github.com/go-pdf/fpdf"
)

// RenderChangeRequestPDF is the bespoke renderer for the Change
// Request Form. A change request is a formal, single-page artefact
// with a clear decision block at the bottom — approved, rejected, or
// deferred. The layout reflects that: a header strip with the request
// ID and a colour-coded decision badge, a requester KV block, the
// change description, a 2x2 impact-analysis grid, and a sign-off
// block.
//
// Layout:
//
//	Header strip:    Request ID  ·  status badge (green/red/amber)
//	Requester KV:    Requested by / Date
//	Section: Change Description (FieldText)
//	Section: Reason (FieldText)
//	Impact grid (2x2):  Scope | Schedule
//	                    Cost  | Risk
//	Decision block:  rationale + approver
//	Footer: generation timestamp
func RenderChangeRequestPDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("P")
	pdf.SetMargins(20, 18, 20)
	pdf.SetAutoPageBreak(true, 18)
	pdf.SetTitle("Change Request", true)
	pdf.AddPage()

	requestID := getString(content, "request_id", "")
	decision := strings.ToLower(strings.TrimSpace(getString(content, "decision", "")))

	// Title block
	pdf.SetFont("Helvetica", "B", 22)
	pdf.Cell(0, 12, projectName)
	pdf.Ln(13)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "Change Request Form")
	pdf.Ln(8)
	pdf.SetTextColor(0, 0, 0)

	// Header strip with request ID + decision badge
	drawCRHeaderStrip(pdf, requestID, decision)
	pdf.Ln(6)

	// Requester block
	requestedBy := getString(content, "requested_by", "")
	requestedAt := getString(content, "requested_at", "")
	if requestedBy != "" || requestedAt != "" {
		drawCRRequesterBlock(pdf, requestedBy, requestedAt)
		pdf.Ln(2)
	}

	// Description + reason
	crSection(pdf, "Change Description", getString(content, "description", ""))
	crSection(pdf, "Reason", getString(content, "reason", ""))

	// 2x2 impact grid
	scope := getString(content, "scope_impact", "")
	schedule := getString(content, "schedule_impact", "")
	risk := getString(content, "risk_impact", "")
	costImpact, _ := content["cost_impact"].(float64)
	if scope != "" || schedule != "" || risk != "" || costImpact != 0 {
		crHeading(pdf, "Impact Analysis")
		drawCRImpactGrid(pdf, scope, schedule, costImpact, risk)
	}

	// Decision block
	drawCRDecisionBlock(pdf,
		decision,
		getString(content, "decision_rationale", ""),
		getString(content, "approver", ""))

	DrawCompactSignatureBox(pdf, projectName, time.Now().Format("2006-01-02"))

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// drawCRHeaderStrip renders the request ID on the left and a coloured
// decision badge on the right. If decision is empty/pending, the badge
// reads "Pending" in slate.
func drawCRHeaderStrip(pdf *fpdf.Fpdf, requestID, decision string) {
	startY := pdf.GetY()
	bodyW := 170.0 // portrait A4 body width

	// Left: Request ID block
	pdf.SetFillColor(243, 244, 246)
	pdf.SetDrawColor(209, 213, 219)
	pdf.Rect(20, startY, bodyW-60, 12, "FD")
	pdf.SetXY(22, startY+1.5)
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetTextColor(75, 85, 99)
	pdf.CellFormat(40, 4, "REQUEST ID", "", 0, "L", false, 0, "")
	pdf.SetXY(22, startY+5.5)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(17, 24, 39)
	idLabel := requestID
	if idLabel == "" {
		idLabel = "(unassigned)"
	}
	pdf.CellFormat(bodyW-64, 5, idLabel, "", 0, "L", false, 0, "")

	// Right: decision badge
	badgeLabel, br, bg, bb := crDecisionBadge(decision)
	pdf.SetFillColor(br, bg, bb)
	pdf.SetDrawColor(br, bg, bb)
	pdf.Rect(20+bodyW-55, startY, 55, 12, "F")
	pdf.SetXY(20+bodyW-55, startY+1.5)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 8)
	pdf.CellFormat(55, 4, "DECISION", "", 0, "C", false, 0, "")
	pdf.SetXY(20+bodyW-55, startY+5.5)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.CellFormat(55, 5, badgeLabel, "", 0, "C", false, 0, "")

	pdf.SetXY(20, startY+12)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
	pdf.SetDrawColor(0, 0, 0)
}

// crDecisionBadge maps a decision string to (label, r, g, b). Unknown
// values fall through to "Pending" / slate.
func crDecisionBadge(decision string) (string, int, int, int) {
	switch decision {
	case "approved", "accepted", "yes":
		return "APPROVED", 21, 128, 61 // green-700
	case "rejected", "denied", "no":
		return "REJECTED", 185, 28, 28 // red-700
	case "deferred", "pending", "on hold", "on_hold", "hold":
		return "DEFERRED", 180, 83, 9 // amber-700
	default:
		return "PENDING", 71, 85, 105 // slate-600
	}
}

func drawCRRequesterBlock(pdf *fpdf.Fpdf, requestedBy, requestedAt string) {
	pdf.SetFont("Helvetica", "B", 10)
	pdf.CellFormat(40, 6, "Requested by:", "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 10)
	pdf.CellFormat(0, 6, requestedBy, "", 0, "L", false, 0, "")
	pdf.Ln(-1)
	if requestedAt != "" {
		pdf.SetFont("Helvetica", "B", 10)
		pdf.CellFormat(40, 6, "Date:", "", 0, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 10)
		pdf.CellFormat(0, 6, requestedAt, "", 0, "L", false, 0, "")
		pdf.Ln(-1)
	}
}

func crHeading(pdf *fpdf.Fpdf, text string) {
	pdf.Ln(3)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(0, 80, 130)
	pdf.Cell(0, 7, text)
	pdf.Ln(7)
	pdf.SetTextColor(0, 0, 0)
}

func crSection(pdf *fpdf.Fpdf, heading, body string) {
	if body == "" {
		return
	}
	crHeading(pdf, heading)
	pdf.SetFont("Helvetica", "", 10)
	pdf.MultiCell(0, 5, body, "", "L", false)
	pdf.Ln(2)
}

// drawCRImpactGrid renders the four impact dimensions in a 2x2 grid.
// Each cell shows a small heading + body text; the cost cell uses a
// formatted money value instead of free text.
func drawCRImpactGrid(pdf *fpdf.Fpdf, scope, schedule string, cost float64, risk string) {
	cellW := 85.0
	cellH := 24.0
	startX := 20.0
	startY := pdf.GetY()

	costStr := ""
	if cost != 0 {
		costStr = fmt.Sprintf("USD %s", formatMoney(cost))
	}

	cells := []struct {
		title, body string
		x, y        float64
	}{
		{"Scope Impact", crFallback(scope), startX, startY},
		{"Schedule Impact", crFallback(schedule), startX + cellW, startY},
		{"Cost Impact", crFallback(costStr), startX, startY + cellH},
		{"Risk Impact", crFallback(risk), startX + cellW, startY + cellH},
	}

	pdf.SetDrawColor(209, 213, 219)
	for _, c := range cells {
		pdf.Rect(c.x, c.y, cellW, cellH, "D")
		pdf.SetXY(c.x+2, c.y+1.5)
		pdf.SetFont("Helvetica", "B", 9)
		pdf.SetTextColor(75, 85, 99)
		pdf.CellFormat(cellW-4, 4, c.title, "", 0, "L", false, 0, "")
		pdf.SetXY(c.x+2, c.y+6)
		pdf.SetFont("Helvetica", "", 9)
		pdf.SetTextColor(17, 24, 39)
		pdf.MultiCell(cellW-4, 4.5, c.body, "", "L", false)
	}
	pdf.SetXY(startX, startY+2*cellH)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetDrawColor(0, 0, 0)
	pdf.Ln(4)
}

func crFallback(s string) string {
	if s == "" {
		return "—"
	}
	return s
}

// drawCRDecisionBlock renders the rationale + approver lines and an
// explicit signature line. Shown regardless of decision so the form
// always has a sign-off slot.
func drawCRDecisionBlock(pdf *fpdf.Fpdf, decision, rationale, approver string) {
	crHeading(pdf, "Decision")
	if rationale != "" {
		pdf.SetFont("Helvetica", "B", 10)
		pdf.CellFormat(40, 6, "Rationale:", "", 0, "L", false, 0, "")
		pdf.Ln(-1)
		pdf.SetFont("Helvetica", "", 10)
		pdf.MultiCell(0, 5, rationale, "", "L", false)
		pdf.Ln(2)
	}

	// Sign-off line
	pdf.Ln(8)
	pdf.SetDrawColor(150, 150, 150)
	signY := pdf.GetY()
	pdf.Line(20, signY, 100, signY)
	pdf.SetXY(20, signY+1)
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(110, 110, 110)
	pdf.CellFormat(80, 4, "Approver signature", "", 0, "L", false, 0, "")

	if approver != "" {
		pdf.SetXY(20, signY-5)
		pdf.SetFont("Helvetica", "B", 10)
		pdf.SetTextColor(17, 24, 39)
		pdf.CellFormat(80, 4, approver, "", 0, "L", false, 0, "")
	}
	pdf.SetTextColor(0, 0, 0)
	pdf.SetDrawColor(0, 0, 0)
	pdf.SetY(signY + 8)
}
