// SPDX-FileCopyrightText: 2026 The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// RenderProjectClosurePDF is the bespoke renderer for the Project
// Closure document. It's a hybrid layout: prose for the closure
// narrative + a table for the structured "Lessons learned" entries
// + a sign-off block.
//
// Layout:
//
//	Title bar:                Project name + "Project Closure"
//	Header line:              Closure date (right-aligned)
//	Section: Objectives met   (FieldText body)
//	Section: Deliverables accepted (StringArr, bulleted)
//	Section: Outstanding items     (StringArr, bulleted; red tint
//	                                because anything left open at
//	                                closure is a flag for the
//	                                receiver)
//	Section: Contracts closed (StringArr, bulleted)
//	Lessons learned table:    Category | Lesson | Recommendation
//	Footer line:              Final budget (actual)
//	Sign-off block:           one signature line
func RenderProjectClosurePDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("P")
	pdf.SetMargins(20, 18, 20)
	pdf.SetAutoPageBreak(true, 18)
	pdf.SetTitle("Project Closure", true)
	pdf.AddPage()

	// Title
	pdf.SetFont("Helvetica", "B", 22)
	pdf.Cell(0, 12, projectName)
	pdf.Ln(13)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "Project Closure")
	pdf.Ln(5)
	if d := getStringClo(content, "closure_date"); d != "" {
		pdf.Cell(0, 6, "Closed: "+d)
		pdf.Ln(8)
	}
	pdf.SetTextColor(0, 0, 0)

	cloSection(pdf, "Objectives met", getStringClo(content, "objectives_met"))
	cloBullets(pdf, "Deliverables accepted", getStringSliceClo(content, "deliverables_accepted"), false)
	cloBullets(pdf, "Outstanding items", getStringSliceClo(content, "outstanding_items"), true)
	cloBullets(pdf, "Contracts closed", getStringSliceClo(content, "contracts_closed"), false)

	drawLessonsLearnedTable(pdf, getObjectSliceClo(content, "lessons_learned"))

	// Final budget summary
	if budget, ok := content["final_budget_actual"].(float64); ok && budget != 0 {
		pdf.Ln(4)
		pdf.SetFont("Helvetica", "B", 10)
		pdf.SetTextColor(0, 80, 130)
		pdf.Cell(50, 6, "Final budget (actual):")
		pdf.SetFont("Helvetica", "", 10)
		pdf.SetTextColor(0, 0, 0)
		pdf.Cell(0, 6, fmt.Sprintf("%.2f", budget))
		pdf.Ln(6)
	}

	// Sign-off
	if signoff := getStringClo(content, "stakeholder_signoff"); signoff != "" {
		pdf.Ln(4)
		pdf.SetFont("Helvetica", "B", 11)
		pdf.SetTextColor(0, 80, 130)
		pdf.Cell(0, 6, "Stakeholder sign-off")
		pdf.Ln(7)
		pdf.SetTextColor(0, 0, 0)
		pdf.SetFont("Helvetica", "", 10)
		pdf.MultiCell(0, 5, signoff, "", "L", false)
	}
	drawClosureSignatureLine(pdf)

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func cloHeading(pdf *gofpdf.Fpdf, text string, redTint bool) {
	pdf.Ln(3)
	pdf.SetFont("Helvetica", "B", 12)
	if redTint {
		pdf.SetTextColor(180, 30, 30)
	} else {
		pdf.SetTextColor(0, 80, 130)
	}
	pdf.Cell(0, 7, text)
	pdf.Ln(7)
	pdf.SetTextColor(0, 0, 0)
}

func cloSection(pdf *gofpdf.Fpdf, heading, body string) {
	if body == "" {
		return
	}
	cloHeading(pdf, heading, false)
	pdf.SetFont("Helvetica", "", 10)
	pdf.MultiCell(0, 5, body, "", "L", false)
	pdf.Ln(1)
}

func cloBullets(pdf *gofpdf.Fpdf, heading string, items []string, redTint bool) {
	if len(items) == 0 {
		return
	}
	cloHeading(pdf, heading, redTint)
	pdf.SetFont("Helvetica", "", 10)
	if redTint {
		pdf.SetTextColor(120, 0, 0)
	}
	for _, item := range items {
		pdf.Cell(5, 5, "•")
		pdf.MultiCell(0, 5, item, "", "L", false)
	}
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(1)
}

// drawLessonsLearnedTable renders the structured lessons-learned
// array as a three-column table.
func drawLessonsLearnedTable(pdf *gofpdf.Fpdf, lessons []map[string]interface{}) {
	if len(lessons) == 0 {
		return
	}
	cloHeading(pdf, "Lessons learned", false)

	cols := []struct {
		label string
		w     float64
	}{
		{"Category", 35},
		{"Lesson", 67},
		{"Recommendation", 68},
	}

	// Header
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(30, 41, 59)
	pdf.SetTextColor(241, 245, 249)
	pdf.SetDrawColor(100, 116, 139)
	for _, c := range cols {
		pdf.CellFormat(c.w, 7, c.label, "1", 0, "L", true, 0, "")
	}
	pdf.Ln(-1)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetFillColor(255, 255, 255)

	for _, l := range lessons {
		pdf.CellFormat(cols[0].w, 6, truncClo(getStringClo(l, "category"), 30), "1", 0, "L", false, 0, "")
		pdf.CellFormat(cols[1].w, 6, truncClo(getStringClo(l, "lesson"), 62), "1", 0, "L", false, 0, "")
		pdf.CellFormat(cols[2].w, 6, truncClo(getStringClo(l, "recommendation"), 64), "1", 0, "L", false, 0, "")
		pdf.Ln(-1)
	}
}

// drawClosureSignatureLine renders the project manager's signature
// line at the bottom — single party because closure is from the PM
// to the sponsor (the sponsor's signature is on the Charter).
func drawClosureSignatureLine(pdf *gofpdf.Fpdf) {
	pdf.Ln(12)
	const lineW = 110.0
	x := 20.0
	pdf.SetDrawColor(100, 100, 100)
	pdf.Line(x, pdf.GetY()+4, x+lineW, pdf.GetY()+4)
	pdf.Ln(6)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.SetX(x)
	pdf.Cell(lineW, 4, "Project Manager — name / date")
	pdf.SetTextColor(0, 0, 0)
}

// Local helpers — kept per-renderer per AGENT.md §10.
func getStringClo(m map[string]interface{}, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}

func getStringSliceClo(m map[string]interface{}, key string) []string {
	v, ok := m[key].([]interface{})
	if !ok {
		return nil
	}
	out := make([]string, 0, len(v))
	for _, x := range v {
		if s, ok := x.(string); ok && s != "" {
			out = append(out, s)
		}
	}
	return out
}

func getObjectSliceClo(m map[string]interface{}, key string) []map[string]interface{} {
	v, ok := m[key].([]interface{})
	if !ok {
		return nil
	}
	out := make([]map[string]interface{}, 0, len(v))
	for _, x := range v {
		if obj, ok := x.(map[string]interface{}); ok {
			out = append(out, obj)
		}
	}
	return out
}

func truncClo(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "…"
}
