// SPDX-FileCopyrightText: 2026 The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"sort"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// RenderCommunicationPlanPDF is the bespoke renderer for the
// Communication Plan document. The schema's only meaningful field is
// `channels`, an object array carrying (channel, audience, purpose,
// frequency, owner). The canonical print layout for this kind is a
// landscape table grouped by audience, so this renderer is genuinely
// table-shaped rather than prose-shaped — same pattern as Risk
// Register.
//
// Layout:
//
//	Header: project name + "Communication Plan"
//	One block per audience group (audience = primary axis):
//	  Audience label
//	  Channels table:
//	    Channel | Frequency | Purpose | Owner
//	  rows in their input order; channel column tinted by cadence
//	  band (daily=red, weekly=cyan, monthly=amber, on-demand=slate).
//	Footer: timestamp.
//
// Why group by audience: the most common reader question when picking
// up a communication plan is "what do I need to do for stakeholder
// X?" — grouping by audience makes that a one-block scan rather than
// a multi-row filter.
func RenderCommunicationPlanPDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("L") // landscape for wide tables
	pdf.SetMargins(15, 15, 15)
	pdf.SetAutoPageBreak(true, 15)
	pdf.SetTitle("Communication Plan", true)
	pdf.AddPage()

	// Title block
	pdf.SetFont("Helvetica", "B", 20)
	pdf.Cell(0, 11, projectName)
	pdf.Ln(11)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "Communication Plan")
	pdf.Ln(10)
	pdf.SetTextColor(0, 0, 0)

	// Pull the channels array and group by audience (case-insensitive
	// match; an empty audience falls into "(unassigned)").
	rows := normaliseChannels(getObjectSliceC(content, "channels"))
	if len(rows) == 0 {
		pdf.SetFont("Helvetica", "I", 10)
		pdf.SetTextColor(120, 120, 120)
		pdf.Cell(0, 6, "No channels defined yet.")
		pdf.SetTextColor(0, 0, 0)
	} else {
		grouped := groupByAudience(rows)
		for _, group := range grouped {
			drawAudienceBlock(pdf, group.Audience, group.Rows)
			pdf.Ln(3)
		}
	}

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// channelRow is the typed form of one row in the channels array.
type channelRow struct {
	Channel   string
	Audience  string
	Purpose   string
	Frequency string
	Owner     string
}

// audienceGroup bundles rows under one display audience.
type audienceGroup struct {
	Audience string
	Rows     []channelRow
}

func normaliseChannels(raw []map[string]interface{}) []channelRow {
	out := make([]channelRow, 0, len(raw))
	for _, r := range raw {
		out = append(out, channelRow{
			Channel:   getStringC(r, "channel"),
			Audience:  getStringC(r, "audience"),
			Purpose:   getStringC(r, "purpose"),
			Frequency: getStringC(r, "frequency"),
			Owner:     getStringC(r, "owner"),
		})
	}
	return out
}

// groupByAudience produces a slice of (audience, rows) pairs ordered
// alphabetically by audience, with "(unassigned)" last. Within a
// group, row order from the input is preserved.
func groupByAudience(rows []channelRow) []audienceGroup {
	buckets := map[string][]channelRow{}
	for _, r := range rows {
		key := r.Audience
		if key == "" {
			key = "(unassigned)"
		}
		buckets[key] = append(buckets[key], r)
	}
	keys := make([]string, 0, len(buckets))
	for k := range buckets {
		keys = append(keys, k)
	}
	sort.SliceStable(keys, func(i, j int) bool {
		// "(unassigned)" sorts last.
		if keys[i] == "(unassigned)" {
			return false
		}
		if keys[j] == "(unassigned)" {
			return true
		}
		return keys[i] < keys[j]
	})
	out := make([]audienceGroup, 0, len(keys))
	for _, k := range keys {
		out = append(out, audienceGroup{Audience: k, Rows: buckets[k]})
	}
	return out
}

// drawAudienceBlock renders one (audience, rows) group as a labelled
// table.
func drawAudienceBlock(pdf *gofpdf.Fpdf, audience string, rows []channelRow) {
	// Audience heading
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(0, 80, 130)
	pdf.Cell(0, 7, audience)
	pdf.Ln(7)
	pdf.SetTextColor(0, 0, 0)

	cols := []struct {
		label string
		w     float64
	}{
		{"Channel", 45},
		{"Frequency", 35},
		{"Purpose", 110},
		{"Owner", 77},
	}

	// Header row
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(30, 41, 59)
	pdf.SetTextColor(241, 245, 249)
	pdf.SetDrawColor(100, 116, 139)
	for _, c := range cols {
		pdf.CellFormat(c.w, 7, c.label, "1", 0, "L", true, 0, "")
	}
	pdf.Ln(-1)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFont("Helvetica", "", 9)

	for _, r := range rows {
		rr, gg, bb := cadenceColor(r.Frequency)
		pdf.SetFillColor(rr, gg, bb)
		pdf.SetTextColor(255, 255, 255)
		pdf.CellFormat(cols[0].w, 6, truncC(r.Channel, 38), "1", 0, "L", true, 0, "")
		pdf.SetTextColor(0, 0, 0)
		pdf.SetFillColor(255, 255, 255)
		pdf.CellFormat(cols[1].w, 6, truncC(r.Frequency, 30), "1", 0, "L", false, 0, "")
		pdf.CellFormat(cols[2].w, 6, truncC(r.Purpose, 98), "1", 0, "L", false, 0, "")
		pdf.CellFormat(cols[3].w, 6, truncC(r.Owner, 70), "1", 0, "L", false, 0, "")
		pdf.Ln(-1)
	}
}

// cadenceColor maps a frequency string (case-insensitive substring
// match) to a tint band. Unknown values fall to slate.
func cadenceColor(freq string) (int, int, int) {
	f := lowerC(freq)
	switch {
	case containsC(f, "daily"), containsC(f, "every day"):
		return 185, 28, 28 // red
	case containsC(f, "weekly"), containsC(f, "biweekly"):
		return 14, 116, 144 // cyan
	case containsC(f, "monthly"), containsC(f, "quarter"):
		return 180, 83, 9 // amber
	case containsC(f, "on-demand"), containsC(f, "ad-hoc"), containsC(f, "as needed"):
		return 71, 85, 105 // slate
	}
	return 71, 85, 105
}

// ---- Local helpers (same pattern as the other bespoke renderers) ----

func getStringC(m map[string]interface{}, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}

func getObjectSliceC(m map[string]interface{}, key string) []map[string]interface{} {
	v, ok := m[key].([]interface{})
	if !ok {
		return nil
	}
	out := make([]map[string]interface{}, 0, len(v))
	for _, x := range v {
		if obj, ok := x.(map[string]interface{}); ok {
			out = append(out, obj)
		}
	}
	return out
}

func truncC(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "…"
}

func lowerC(s string) string {
	b := []byte(s)
	for i, c := range b {
		if c >= 'A' && c <= 'Z' {
			b[i] = c + ('a' - 'A')
		}
	}
	return string(b)
}

func containsC(haystack, needle string) bool {
	if needle == "" {
		return true
	}
	if len(haystack) < len(needle) {
		return false
	}
	for i := 0; i <= len(haystack)-len(needle); i++ {
		if haystack[i:i+len(needle)] == needle {
			return true
		}
	}
	return false
}
