// SPDX-FileCopyrightText: 2026 James L. Burns and The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"sort"
	"time"

	"github.com/go-pdf/fpdf"
)

// RenderExecutionPlanPDF is the bespoke renderer for the Project
// Execution Plan. The novel layout element is an **inline mini-Gantt**
// column: each task row shows a horizontal segment positioned along a
// shared project-timeline track, so the reader sees who-does-what-when
// at a single glance. Pairs the Team Charter bar-chart trick with a
// task-table sort.
//
// Layout:
//
//	Title bar (landscape A4)
//	Summary banner: tasks, total cost, project window
//	Tasks table:
//	  Task | Owner | Start | End | Days | Cost | Timeline (inline segment)
//	Total-cost footer row
//	Resources legend appended for any task with a non-empty resources field
//	Footer: generation timestamp
func RenderExecutionPlanPDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("L")
	pdf.SetMargins(15, 15, 15)
	pdf.SetAutoPageBreak(true, 15)
	pdf.SetTitle("Project Execution Plan", true)
	pdf.AddPage()

	// Title
	pdf.SetFont("Helvetica", "B", 20)
	pdf.Cell(0, 11, projectName)
	pdf.Ln(11)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "Project Execution Plan")
	pdf.Ln(8)
	pdf.SetTextColor(0, 0, 0)

	tasks := normaliseExecutionTasks(getObjectSlice(content, "tasks"))
	window := computeProjectWindow(tasks)

	// Summary banner
	totalCost := sumExecutionCost(tasks)
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetTextColor(30, 41, 59)
	pdf.Cell(0, 6, fmt.Sprintf(
		"Tasks: %d  \xc2\xb7  Total cost: USD %s  \xc2\xb7  Window: %s \xe2\x86\x92 %s (%d days)",
		len(tasks), formatMoney(totalCost),
		shortExecDate(window.Start), shortExecDate(window.End), window.Days))
	pdf.Ln(8)
	pdf.SetTextColor(0, 0, 0)

	if len(tasks) == 0 {
		pdf.SetFont("Helvetica", "I", 10)
		pdf.SetTextColor(120, 120, 120)
		pdf.Cell(0, 6, "No tasks recorded yet.")
		pdf.SetTextColor(0, 0, 0)
	} else {
		// Sort by start date ascending; empty starts sink to the bottom.
		sort.SliceStable(tasks, func(i, j int) bool {
			si, sj := tasks[i].StartDate, tasks[j].StartDate
			if (si == "") != (sj == "") {
				return si != ""
			}
			return si < sj
		})
		drawExecutionTable(pdf, tasks, window)
	}

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// executionTask is the typed view of one tasks row.
type executionTask struct {
	Name      string
	Owner     string
	StartDate string
	EndDate   string
	Resources string
	Cost      float64
}

func normaliseExecutionTasks(raw []map[string]interface{}) []executionTask {
	out := make([]executionTask, 0, len(raw))
	for _, r := range raw {
		out = append(out, executionTask{
			Name:      getStringExec(r, "name"),
			Owner:     getStringExec(r, "owner"),
			StartDate: getStringExec(r, "start_date"),
			EndDate:   getStringExec(r, "end_date"),
			Resources: getStringExec(r, "resources"),
			Cost:      getFloatExec(r, "cost"),
		})
	}
	return out
}

func sumExecutionCost(tasks []executionTask) float64 {
	var sum float64
	for _, t := range tasks {
		sum += t.Cost
	}
	return sum
}

// projectWindow describes the overall start→end span across all
// tasks, used to anchor the inline Gantt column.
type projectWindow struct {
	Start time.Time
	End   time.Time
	Days  int
}

func computeProjectWindow(tasks []executionTask) projectWindow {
	var minT, maxT time.Time
	for _, t := range tasks {
		s := parseDate(t.StartDate)
		e := parseDate(t.EndDate)
		if !s.IsZero() && (minT.IsZero() || s.Before(minT)) {
			minT = s
		}
		// A task with only an end date still extends the window.
		if !e.IsZero() && (maxT.IsZero() || e.After(maxT)) {
			maxT = e
		}
		// Also let the start date extend the window if no end exists.
		if !s.IsZero() && (maxT.IsZero() || s.After(maxT)) {
			maxT = s
		}
	}
	days := 0
	if !minT.IsZero() && !maxT.IsZero() {
		days = int(maxT.Sub(minT).Hours()/24) + 1
	}
	return projectWindow{Start: minT, End: maxT, Days: days}
}

// parseDate accepts either YYYY-MM-DD or RFC3339. Empty / unparseable
// strings return the zero Time.
func parseDate(s string) time.Time {
	if s == "" {
		return time.Time{}
	}
	for _, layout := range []string{"2006-01-02", time.RFC3339, time.RFC3339Nano} {
		if t, err := time.Parse(layout, s); err == nil {
			return t
		}
	}
	return time.Time{}
}

// drawExecutionTable renders the tasks with an inline timeline segment
// in the rightmost column.
func drawExecutionTable(pdf *fpdf.Fpdf, tasks []executionTask, window projectWindow) {
	cols := []struct {
		header string
		w      float64
		align  string
	}{
		{"Task", 55, "L"},
		{"Owner", 28, "L"},
		{"Start", 22, "L"},
		{"End", 22, "L"},
		{"Days", 14, "R"},
		{"Cost (USD)", 24, "R"},
		{"Timeline", 102, "L"},
	}

	// Header
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(30, 41, 59)
	pdf.SetTextColor(241, 245, 249)
	pdf.SetDrawColor(100, 116, 139)
	for _, c := range cols {
		pdf.CellFormat(c.w, 7, c.header, "1", 0, c.align, true, 0, "")
	}
	pdf.Ln(-1)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFont("Helvetica", "", 8)

	rowH := 7.0
	for i, t := range tasks {
		if i%2 == 0 {
			pdf.SetFillColor(248, 250, 252)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}

		startY := pdf.GetY()

		pdf.CellFormat(cols[0].w, rowH, truncExec(t.Name, 50), "1", 0, "L", true, 0, "")
		pdf.CellFormat(cols[1].w, rowH, truncExec(t.Owner, 24), "1", 0, "L", true, 0, "")
		pdf.CellFormat(cols[2].w, rowH, shortExecDate(parseDate(t.StartDate)), "1", 0, "L", true, 0, "")
		pdf.CellFormat(cols[3].w, rowH, shortExecDate(parseDate(t.EndDate)), "1", 0, "L", true, 0, "")
		pdf.CellFormat(cols[4].w, rowH, taskDurationLabel(t.StartDate, t.EndDate), "1", 0, "R", true, 0, "")

		costLabel := "—"
		if t.Cost != 0 {
			costLabel = formatMoney(t.Cost)
		}
		pdf.CellFormat(cols[5].w, rowH, costLabel, "1", 0, "R", true, 0, "")

		// Timeline cell — empty border, then overlay segment
		tlX := pdf.GetX()
		pdf.CellFormat(cols[6].w, rowH, "", "1", 0, "L", true, 0, "")
		drawTimelineSegment(pdf, tlX, startY, cols[6].w, rowH, t, window)
		pdf.Ln(-1)
	}

	// Total row
	pdf.SetFillColor(226, 232, 240)
	pdf.SetFont("Helvetica", "B", 9)
	leftW := cols[0].w + cols[1].w + cols[2].w + cols[3].w + cols[4].w
	pdf.CellFormat(leftW, 7, "Total", "1", 0, "R", true, 0, "")
	pdf.CellFormat(cols[5].w, 7, formatMoney(sumExecutionCost(tasks)), "1", 0, "R", true, 0, "")
	pdf.CellFormat(cols[6].w, 7, "", "1", 0, "L", true, 0, "")
	pdf.Ln(-1)
}

// drawTimelineSegment renders one task's [start, end] window as a
// horizontal bar positioned along the project's full timeline track.
// Padding on either side of the cell so the segment doesn't touch the
// cell border.
func drawTimelineSegment(pdf *fpdf.Fpdf, x, y, w, h float64, t executionTask, window projectWindow) {
	const padX = 2.0
	const padY = 2.0
	trackX := x + padX
	trackY := y + padY
	trackW := w - 2*padX
	trackH := h - 2*padY

	// Track (background)
	pdf.SetFillColor(229, 231, 235)
	pdf.Rect(trackX, trackY, trackW, trackH, "F")

	start := parseDate(t.StartDate)
	end := parseDate(t.EndDate)
	if start.IsZero() && end.IsZero() {
		return
	}
	if start.IsZero() {
		start = end
	}
	if end.IsZero() {
		end = start
	}
	if window.Start.IsZero() || window.End.IsZero() || window.Days <= 0 {
		return
	}

	totalDays := float64(window.Days)
	offsetDays := start.Sub(window.Start).Hours() / 24
	taskDays := end.Sub(start).Hours()/24 + 1
	if taskDays < 1 {
		taskDays = 1
	}

	segX := trackX + trackW*offsetDays/totalDays
	segW := trackW * taskDays / totalDays
	if segW < 0.8 {
		segW = 0.8 // ensure single-day tasks are visible
	}
	if segX+segW > trackX+trackW {
		segW = trackX + trackW - segX
	}

	pdf.SetFillColor(30, 64, 175) // blue-800
	pdf.Rect(segX, trackY, segW, trackH, "F")
}

// taskDurationLabel returns the integer day count for a task. Empty if
// either endpoint is missing.
func taskDurationLabel(start, end string) string {
	s := parseDate(start)
	e := parseDate(end)
	if s.IsZero() || e.IsZero() {
		return "—"
	}
	days := int(e.Sub(s).Hours()/24) + 1
	if days < 1 {
		days = 1
	}
	return fmt.Sprintf("%d", days)
}

// shortExecDate accepts either time.Time or string. For time.Time it
// returns YYYY-MM-DD (empty for zero). For string it truncates to 10
// chars.
func shortExecDate(v interface{}) string {
	switch x := v.(type) {
	case time.Time:
		if x.IsZero() {
			return "—"
		}
		return x.Format("2006-01-02")
	case string:
		if len(x) >= 10 {
			return x[:10]
		}
		if x == "" {
			return "—"
		}
		return x
	}
	return "—"
}

func getStringExec(m map[string]interface{}, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}

func getFloatExec(m map[string]interface{}, key string) float64 {
	if v, ok := m[key].(float64); ok {
		return v
	}
	return 0
}

func truncExec(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "\xe2\x80\xa6" // …
}
