// SPDX-FileCopyrightText: 2026 James L. Burns and The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// RenderIssueLogPDF is the bespoke renderer for the Issue Log. The
// canonical print layout is a landscape table grouped into two bands:
// Open issues (anything not resolved/closed/done) shown first, sorted
// by severity descending, then Resolved issues. Severity drives the
// first-column tint, matching the Risk Register pattern.
//
// Layout:
//
//	Title bar (landscape A4)
//	Severity legend chips
//	Counts banner: "N open / M resolved"
//	Open issues table   (band header "Open")
//	Resolved table      (band header "Resolved", muted)
//	Footer: generation timestamp
func RenderIssueLogPDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("L")
	pdf.SetMargins(15, 15, 15)
	pdf.SetAutoPageBreak(true, 15)
	pdf.SetTitle("Issue Log", true)
	pdf.AddPage()

	// Title
	pdf.SetFont("Helvetica", "B", 20)
	pdf.Cell(0, 11, projectName)
	pdf.Ln(11)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "Issue Log")
	pdf.Ln(8)
	pdf.SetTextColor(0, 0, 0)

	// Legend
	drawIssueLegend(pdf)
	pdf.Ln(7)

	issues := normaliseIssues(getObjectSlice(content, "issues"))
	open, resolved := partitionIssues(issues)

	// Counts banner
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetTextColor(60, 60, 60)
	pdf.Cell(0, 6, fmt.Sprintf("%d open  ·  %d resolved  ·  %d total",
		len(open), len(resolved), len(issues)))
	pdf.Ln(8)
	pdf.SetTextColor(0, 0, 0)

	if len(issues) == 0 {
		pdf.SetFont("Helvetica", "I", 10)
		pdf.SetTextColor(120, 120, 120)
		pdf.Cell(0, 6, "No issues recorded yet.")
		pdf.SetTextColor(0, 0, 0)
	} else {
		if len(open) > 0 {
			drawIssueBandHeader(pdf, "Open", 185, 28, 28)
			drawIssueTable(pdf, open, false)
			pdf.Ln(4)
		}
		if len(resolved) > 0 {
			drawIssueBandHeader(pdf, "Resolved", 71, 85, 105)
			drawIssueTable(pdf, resolved, true)
		}
	}

	DrawCompactSignatureBox(pdf, projectName, time.Now().Format("2006-01-02"))

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// issue is the typed view of one issue-log row.
type issue struct {
	ID          string
	Description string
	RaisedBy    string
	RaisedAt    string
	Severity    string
	Owner       string
	Status      string
	Resolution  string
}

func normaliseIssues(raw []map[string]interface{}) []issue {
	out := make([]issue, 0, len(raw))
	for _, r := range raw {
		out = append(out, issue{
			ID:          getStringIssue(r, "id"),
			Description: getStringIssue(r, "description"),
			RaisedBy:    getStringIssue(r, "raised_by"),
			RaisedAt:    getStringIssue(r, "raised_at"),
			Severity:    getStringIssue(r, "severity"),
			Owner:       getStringIssue(r, "owner"),
			Status:      getStringIssue(r, "status"),
			Resolution:  getStringIssue(r, "resolution"),
		})
	}
	return out
}

// partitionIssues splits a slice into open vs resolved based on the
// `status` field. An empty status counts as open. Both partitions are
// sorted by severity descending so the most urgent items lead.
func partitionIssues(issues []issue) (open, resolved []issue) {
	for _, i := range issues {
		if isIssueResolved(i.Status) {
			resolved = append(resolved, i)
		} else {
			open = append(open, i)
		}
	}
	sortBySeverity := func(s []issue) {
		sort.SliceStable(s, func(i, j int) bool {
			return issueSeverityOrder(s[i].Severity) < issueSeverityOrder(s[j].Severity)
		})
	}
	sortBySeverity(open)
	sortBySeverity(resolved)
	return open, resolved
}

// isIssueResolved recognises the common "done" statuses. Comparison
// is case-insensitive and trims whitespace so user-entered values like
// "Closed " or "RESOLVED" all match.
func isIssueResolved(status string) bool {
	s := strings.ToLower(strings.TrimSpace(status))
	switch s {
	case "resolved", "closed", "done", "complete", "completed":
		return true
	}
	return false
}

// issueSeverityOrder maps severity to ascending sort order (lower =
// more severe so it appears at the top).
func issueSeverityOrder(sev string) int {
	switch strings.ToLower(strings.TrimSpace(sev)) {
	case "critical":
		return 0
	case "high":
		return 1
	case "medium":
		return 2
	case "low":
		return 3
	default:
		return 4
	}
}

func issueSeverityColor(sev string) (int, int, int) {
	switch strings.ToLower(strings.TrimSpace(sev)) {
	case "critical":
		return 127, 29, 29
	case "high":
		return 185, 28, 28
	case "medium":
		return 180, 83, 9
	case "low":
		return 14, 116, 144
	default:
		return 71, 85, 105
	}
}

func drawIssueLegend(pdf *gofpdf.Fpdf) {
	pdf.SetFont("Helvetica", "B", 8)
	bands := []struct {
		label   string
		r, g, b int
	}{
		{"Critical", 127, 29, 29},
		{"High", 185, 28, 28},
		{"Medium", 180, 83, 9},
		{"Low", 14, 116, 144},
		{"Other", 71, 85, 105},
	}
	x := pdf.GetX()
	y := pdf.GetY()
	for _, b := range bands {
		pdf.SetFillColor(b.r, b.g, b.b)
		pdf.SetDrawColor(b.r, b.g, b.b)
		pdf.RoundedRect(x, y, 36, 7, 2, "1234", "F")
		pdf.SetTextColor(255, 255, 255)
		pdf.SetXY(x+2, y+1.5)
		pdf.CellFormat(32, 4, b.label, "", 0, "C", false, 0, "")
		x += 39
	}
	pdf.SetXY(15, y+7)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
	pdf.SetDrawColor(0, 0, 0)
}

func drawIssueBandHeader(pdf *gofpdf.Fpdf, label string, r, g, b int) {
	pdf.SetFont("Helvetica", "B", 11)
	pdf.SetFillColor(r, g, b)
	pdf.SetTextColor(255, 255, 255)
	pdf.CellFormat(0, 7, "  "+label, "", 0, "L", true, 0, "")
	pdf.Ln(-1)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
}

// drawIssueTable emits issues as a 7-column landscape table.
// If muted is true, the body uses softer text + fill colours so the
// resolved band visually recedes behind the open band.
func drawIssueTable(pdf *gofpdf.Fpdf, issues []issue, muted bool) {
	cols := []struct {
		header string
		w      float64
		align  string
	}{
		{"ID", 20, "L"},
		{"Severity", 22, "L"},
		{"Raised", 24, "L"},
		{"Owner", 30, "L"},
		{"Status", 26, "L"},
		{"Description", 75, "L"},
		{"Resolution", 70, "L"},
	}

	// Table header
	pdf.SetFont("Helvetica", "B", 9)
	if muted {
		pdf.SetFillColor(100, 116, 139)
	} else {
		pdf.SetFillColor(30, 41, 59)
	}
	pdf.SetTextColor(241, 245, 249)
	pdf.SetDrawColor(100, 116, 139)
	for _, c := range cols {
		pdf.CellFormat(c.w, 7, c.header, "1", 0, c.align, true, 0, "")
	}
	pdf.Ln(-1)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFont("Helvetica", "", 8)

	for _, it := range issues {
		rr, gg, bb := issueSeverityColor(it.Severity)
		if muted {
			rr, gg, bb = mutedColor(rr, gg, bb)
		}
		pdf.SetFillColor(rr, gg, bb)
		pdf.SetTextColor(255, 255, 255)
		pdf.CellFormat(cols[0].w, 6, truncIssue(it.ID, 16), "1", 0, "L", true, 0, "")

		if muted {
			pdf.SetTextColor(110, 110, 110)
		} else {
			pdf.SetTextColor(0, 0, 0)
		}
		pdf.SetFillColor(255, 255, 255)
		pdf.CellFormat(cols[1].w, 6, truncIssue(it.Severity, 18), "1", 0, "L", false, 0, "")
		pdf.CellFormat(cols[2].w, 6, shortIssueDate(it.RaisedAt), "1", 0, "L", false, 0, "")
		pdf.CellFormat(cols[3].w, 6, truncIssue(it.Owner, 25), "1", 0, "L", false, 0, "")
		pdf.CellFormat(cols[4].w, 6, truncIssue(it.Status, 22), "1", 0, "L", false, 0, "")
		pdf.CellFormat(cols[5].w, 6, truncIssue(it.Description, 64), "1", 0, "L", false, 0, "")
		pdf.CellFormat(cols[6].w, 6, truncIssue(it.Resolution, 60), "1", 0, "L", false, 0, "")
		pdf.Ln(-1)
	}
	pdf.SetTextColor(0, 0, 0)
}

// mutedColor blends an RGB triple toward grey so the resolved-band
// severity chip recedes visually without losing its hue entirely.
func mutedColor(r, g, b int) (int, int, int) {
	const grey = 148 // slate-400 baseline
	return (r + grey) / 2, (g + grey) / 2, (b + grey) / 2
}

// shortIssueDate trims an RFC3339-ish timestamp to its YYYY-MM-DD
// prefix so the Raised column stays narrow.
func shortIssueDate(s string) string {
	if len(s) >= 10 {
		return s[:10]
	}
	return s
}

func getStringIssue(m map[string]interface{}, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}

func truncIssue(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "\xe2\x80\xa6" // …
}
