// SPDX-FileCopyrightText: 2026 James L. Burns and The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// RenderProcurementPlanPDF is the bespoke renderer for the Procurement
// Plan. The canonical layout is a landscape table sorted by target
// award date ascending (earliest awards first), with the contract type
// rendered as a colour-coded badge so the buyer can see commercial-
// risk distribution at a glance.
//
// Layout:
//
//	Title bar (landscape A4)
//	Total-budget banner   "Σ items budget: USD X"
//	Contract-type legend  (Fixed Price / T&M / Cost Plus / Other)
//	Procurement table:
//	  Item | Contract | Target Award | Budget | Selection Criteria
//	Footer: generation timestamp
func RenderProcurementPlanPDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("L")
	pdf.SetMargins(15, 15, 15)
	pdf.SetAutoPageBreak(true, 15)
	pdf.SetTitle("Procurement Plan", true)
	pdf.AddPage()

	// Title
	pdf.SetFont("Helvetica", "B", 20)
	pdf.Cell(0, 11, projectName)
	pdf.Ln(11)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "Procurement Plan")
	pdf.Ln(8)
	pdf.SetTextColor(0, 0, 0)

	items := normaliseProcurement(getObjectSlice(content, "items"))

	// Total budget banner
	total := procurementTotal(items)
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetTextColor(30, 41, 59)
	pdf.Cell(0, 6, fmt.Sprintf("Items: %d  \xc2\xb7  Total budget: USD %s",
		len(items), formatMoney(total)))
	pdf.Ln(7)
	pdf.SetTextColor(0, 0, 0)

	// Legend
	drawProcurementLegend(pdf)
	pdf.Ln(7)

	if len(items) == 0 {
		pdf.SetFont("Helvetica", "I", 10)
		pdf.SetTextColor(120, 120, 120)
		pdf.Cell(0, 6, "No procurement items recorded yet.")
		pdf.SetTextColor(0, 0, 0)
	} else {
		// Sort by award date ascending; empty dates sink to the bottom.
		sort.SliceStable(items, func(i, j int) bool {
			ai, aj := items[i].TargetAwardDate, items[j].TargetAwardDate
			if (ai == "") != (aj == "") {
				return ai != "" // non-empty first
			}
			return ai < aj
		})
		drawProcurementTable(pdf, items)
	}

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// procurementItem is the typed view of one item.
type procurementItem struct {
	Item                    string
	ContractType            string
	VendorSelectionCriteria string
	TargetAwardDate         string
	Budget                  float64
}

func normaliseProcurement(raw []map[string]interface{}) []procurementItem {
	out := make([]procurementItem, 0, len(raw))
	for _, r := range raw {
		out = append(out, procurementItem{
			Item:                    getStringProc(r, "item"),
			ContractType:            getStringProc(r, "contract_type"),
			VendorSelectionCriteria: getStringProc(r, "vendor_selection_criteria"),
			TargetAwardDate:         getStringProc(r, "target_award_date"),
			Budget:                  getFloatProc(r, "budget"),
		})
	}
	return out
}

func procurementTotal(items []procurementItem) float64 {
	var sum float64
	for _, i := range items {
		sum += i.Budget
	}
	return sum
}

// contractTypeColor maps a contract type to a colour. Recognises
// common procurement nomenclature; unknown values render in slate.
func contractTypeColor(ct string) (int, int, int) {
	switch normaliseContractType(ct) {
	case "fixed":
		return 21, 128, 61 // green: low risk to buyer
	case "tm":
		return 180, 83, 9 // amber: moderate risk
	case "costplus":
		return 185, 28, 28 // red: high risk to buyer
	case "unit":
		return 14, 116, 144 // cyan: per-unit pricing
	default:
		return 71, 85, 105 // slate: other / unspecified
	}
}

// contractTypeLabel returns the short display label for a contract
// type after normalisation.
func contractTypeLabel(ct string) string {
	switch normaliseContractType(ct) {
	case "fixed":
		return "Fixed Price"
	case "tm":
		return "T&M"
	case "costplus":
		return "Cost Plus"
	case "unit":
		return "Unit Price"
	default:
		if ct == "" {
			return "—"
		}
		return ct
	}
}

// normaliseContractType reduces messy user input ("Time & Materials",
// "time and materials", "T&M") to a canonical token. Comparison is
// case-insensitive and ignores whitespace, ampersands, and the word
// "and".
func normaliseContractType(ct string) string {
	s := strings.ToLower(ct)
	s = strings.ReplaceAll(s, "&", "")
	s = strings.ReplaceAll(s, "-", " ")
	s = strings.ReplaceAll(s, "_", " ")
	s = strings.Join(strings.Fields(s), "")
	s = strings.ReplaceAll(s, "and", "")
	switch {
	case strings.Contains(s, "fixed") || s == "ffp":
		return "fixed"
	case strings.Contains(s, "tm") || strings.Contains(s, "timematerials"):
		return "tm"
	case strings.Contains(s, "costplus") || s == "cpff" || s == "cpif":
		return "costplus"
	case strings.Contains(s, "unit") || strings.Contains(s, "perunit"):
		return "unit"
	}
	return ""
}

func drawProcurementLegend(pdf *gofpdf.Fpdf) {
	pdf.SetFont("Helvetica", "B", 8)
	bands := []struct {
		label string
		key   string
	}{
		{"Fixed Price", "fixed"},
		{"T&M", "tm"},
		{"Cost Plus", "costplus"},
		{"Unit Price", "unit"},
		{"Other", ""},
	}
	x := pdf.GetX()
	y := pdf.GetY()
	for _, b := range bands {
		r, g, bb := contractTypeColor(b.key)
		pdf.SetFillColor(r, g, bb)
		pdf.SetDrawColor(r, g, bb)
		pdf.RoundedRect(x, y, 40, 7, 2, "1234", "F")
		pdf.SetTextColor(255, 255, 255)
		pdf.SetXY(x+2, y+1.5)
		pdf.CellFormat(36, 4, b.label, "", 0, "C", false, 0, "")
		x += 43
	}
	pdf.SetXY(15, y+7)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
	pdf.SetDrawColor(0, 0, 0)
}

func drawProcurementTable(pdf *gofpdf.Fpdf, items []procurementItem) {
	cols := []struct {
		header string
		w      float64
		align  string
	}{
		{"Item", 60, "L"},
		{"Contract", 32, "L"},
		{"Target Award", 28, "L"},
		{"Budget (USD)", 32, "R"},
		{"Vendor Selection Criteria", 115, "L"},
	}

	// Header
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(30, 41, 59)
	pdf.SetTextColor(241, 245, 249)
	pdf.SetDrawColor(100, 116, 139)
	for _, c := range cols {
		pdf.CellFormat(c.w, 7, c.header, "1", 0, c.align, true, 0, "")
	}
	pdf.Ln(-1)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFont("Helvetica", "", 8)

	for idx, it := range items {
		if idx%2 == 0 {
			pdf.SetFillColor(248, 250, 252)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}

		// Item
		pdf.CellFormat(cols[0].w, 6, truncProc(it.Item, 48), "1", 0, "L", true, 0, "")

		// Contract type badge cell
		r, g, b := contractTypeColor(it.ContractType)
		pdf.SetFillColor(r, g, b)
		pdf.SetTextColor(255, 255, 255)
		pdf.SetFont("Helvetica", "B", 8)
		pdf.CellFormat(cols[1].w, 6, contractTypeLabel(it.ContractType), "1", 0, "C", true, 0, "")
		pdf.SetTextColor(0, 0, 0)
		pdf.SetFont("Helvetica", "", 8)

		// Restore alternating fill for remaining cells
		if idx%2 == 0 {
			pdf.SetFillColor(248, 250, 252)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}

		pdf.CellFormat(cols[2].w, 6, shortProcDate(it.TargetAwardDate), "1", 0, "L", true, 0, "")

		budget := "—"
		if it.Budget != 0 {
			budget = formatMoney(it.Budget)
		}
		pdf.CellFormat(cols[3].w, 6, budget, "1", 0, "R", true, 0, "")
		pdf.CellFormat(cols[4].w, 6, truncProc(it.VendorSelectionCriteria, 100), "1", 0, "L", true, 0, "")
		pdf.Ln(-1)
	}

	// Total row
	pdf.SetFillColor(226, 232, 240)
	pdf.SetFont("Helvetica", "B", 9)
	pdf.CellFormat(cols[0].w+cols[1].w+cols[2].w, 7, "Total", "1", 0, "R", true, 0, "")
	pdf.CellFormat(cols[3].w, 7, formatMoney(procurementTotal(items)), "1", 0, "R", true, 0, "")
	pdf.CellFormat(cols[4].w, 7, "", "1", 0, "L", true, 0, "")
	pdf.Ln(-1)
}

func shortProcDate(s string) string {
	if len(s) >= 10 {
		return s[:10]
	}
	return s
}

func getStringProc(m map[string]interface{}, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}

func getFloatProc(m map[string]interface{}, key string) float64 {
	if v, ok := m[key].(float64); ok {
		return v
	}
	return 0
}

func truncProc(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "\xe2\x80\xa6" // …
}
