// SPDX-FileCopyrightText: 2026 James L. Burns and The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// RenderProjectBudgetPDF is the bespoke renderer for the Project
// Budget. The document is table-heavy — cost categories, amounts, and
// notes — so the layout follows the Risk Register landscape pattern
// but with a financial summary footer (subtotal, contingency, grand
// total).
//
// Layout:
//
//	Title bar:        Project name + "Project Budget"
//	Currency note (if not USD)
//	Categories table: Category | Amount | Notes
//	Summary block:    Subtotal, Contingency %, Grand Total (tinted)
//	Footer:           generation timestamp
func RenderProjectBudgetPDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("P")
	pdf.SetMargins(20, 18, 20)
	pdf.SetAutoPageBreak(true, 18)
	pdf.SetTitle("Project Budget", true)
	pdf.AddPage()

	currency := getString(content, "currency", "USD")

	// Title block
	pdf.SetFont("Helvetica", "B", 22)
	pdf.Cell(0, 12, projectName)
	pdf.Ln(13)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, fmt.Sprintf("Project Budget — %s", currency))
	pdf.Ln(9)
	pdf.SetTextColor(0, 0, 0)

	// Categories table
	categories := getObjectSlice(content, "categories")
	subtotal := budgetSubtotal(categories)
	contingencyPct := getFloatBudget(content, "contingency_pct")
	explicitTotal := getFloatBudget(content, "total")

	if len(categories) == 0 {
		pdf.SetFont("Helvetica", "I", 10)
		pdf.SetTextColor(120, 120, 120)
		pdf.Cell(0, 6, "No cost categories recorded yet.")
		pdf.SetTextColor(0, 0, 0)
		pdf.Ln(8)
	} else {
		drawBudgetTable(pdf, categories, currency)
	}

	// Summary block
	drawBudgetSummary(pdf, subtotal, contingencyPct, explicitTotal, currency)

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// drawBudgetTable renders the cost categories as a three-column table.
// Column widths (portrait A4 body = 170mm): Category 60, Amount 40, Notes 70.
func drawBudgetTable(pdf *gofpdf.Fpdf, categories []map[string]interface{}, currency string) {
	cols := []struct {
		header string
		w      float64
		align  string
	}{
		{"Category", 65, "L"},
		{"Amount (" + currency + ")", 40, "R"},
		{"Notes", 65, "L"},
	}

	// Header row
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetFillColor(30, 41, 59)
	pdf.SetTextColor(241, 245, 249)
	for _, c := range cols {
		pdf.CellFormat(c.w, 7, c.header, "1", 0, c.align, true, 0, "")
	}
	pdf.Ln(-1)
	pdf.SetTextColor(0, 0, 0)

	// Alternating-row body
	for i, cat := range categories {
		if i%2 == 0 {
			pdf.SetFillColor(248, 250, 252)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}
		pdf.SetFont("Helvetica", "", 10)
		catName := getStringBudget(cat, "category")
		amount := getFloatBudget(cat, "amount")
		notes := getStringBudget(cat, "notes")
		pdf.CellFormat(cols[0].w, 6, truncBudget(catName, 50), "1", 0, "L", true, 0, "")
		pdf.CellFormat(cols[1].w, 6, formatMoney(amount), "1", 0, "R", true, 0, "")
		pdf.CellFormat(cols[2].w, 6, truncBudget(notes, 50), "1", 0, "L", true, 0, "")
		pdf.Ln(-1)
	}
	pdf.Ln(4)
}

// drawBudgetSummary renders the subtotal, contingency, and grand total.
func drawBudgetSummary(pdf *gofpdf.Fpdf, subtotal, contingencyPct, explicitTotal float64, currency string) {
	contingencyAmt := subtotal * contingencyPct / 100
	grandTotal := subtotal + contingencyAmt
	if explicitTotal > 0 {
		grandTotal = explicitTotal
	}

	summaryX := 90.0 // right-aligned block starting at the centre
	lineH := 7.0

	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(60, 60, 60)

	budgetKV(pdf, summaryX, lineH, "Subtotal", fmt.Sprintf("%s %s", currency, formatMoney(subtotal)))
	if contingencyPct > 0 {
		budgetKV(pdf, summaryX, lineH,
			fmt.Sprintf("Contingency (%.0f%%)", contingencyPct),
			fmt.Sprintf("%s %s", currency, formatMoney(contingencyAmt)))
	}

	// Grand total in a tinted bar
	pdf.Ln(1)
	pdf.SetFillColor(30, 41, 59)
	pdf.SetTextColor(241, 245, 249)
	pdf.SetFont("Helvetica", "B", 11)
	pdf.SetX(summaryX)
	pdf.CellFormat(50, 8, "Grand Total", "1", 0, "L", true, 0, "")
	pdf.CellFormat(30, 8, fmt.Sprintf("%s %s", currency, formatMoney(grandTotal)), "1", 0, "R", true, 0, "")
	pdf.Ln(10)
	pdf.SetTextColor(0, 0, 0)
}

func budgetKV(pdf *gofpdf.Fpdf, startX, h float64, label, value string) {
	pdf.SetX(startX)
	pdf.CellFormat(50, h, label, "", 0, "L", false, 0, "")
	pdf.CellFormat(30, h, value, "", 0, "R", false, 0, "")
	pdf.Ln(-1)
}

func budgetSubtotal(categories []map[string]interface{}) float64 {
	var sum float64
	for _, cat := range categories {
		sum += getFloatBudget(cat, "amount")
	}
	return sum
}

// formatMoney formats a float as a 2-decimal number with thousands
// separators (e.g. 1234567.5 → "1,234,567.50").
func formatMoney(v float64) string {
	s := fmt.Sprintf("%.2f", v)
	// Split at decimal point.
	dotIdx := len(s) - 3
	intPart := s[:dotIdx]
	fracPart := s[dotIdx:]
	// Insert commas every three digits from right.
	var out strings.Builder
	out.Grow(len(intPart) + len(intPart)/3 + 1)
	for i, ch := range intPart {
		if i > 0 && (len(intPart)-i)%3 == 0 {
			out.WriteByte(',')
		}
		out.WriteRune(ch)
	}
	return out.String() + fracPart
}

func getStringBudget(m map[string]interface{}, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}

func getFloatBudget(m map[string]interface{}, key string) float64 {
	if v, ok := m[key].(float64); ok {
		return v
	}
	return 0
}

func truncBudget(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "\xe2\x80\xa6" // …
}
