// SPDX-FileCopyrightText: 2026 James L. Burns and The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// RenderProjectBriefPDF is the bespoke renderer for the Project
// Brief. Per the schema description: "Short, audience-oriented summary
// of the plan for non-PM stakeholders." The layout reflects that —
// approachable, light on formality, with the summary front-and-centre
// and the supporting facts arranged for quick scanning.
//
// Layout:
//
//	Title bar (portrait A4)
//	Summary callout      (accent-boxed, top of document — the answer
//	                      to "what is this project?")
//	Two-tile KPI strip:  Budget | Timeline
//	Section: Goals       (numbered list)
//	Section: Roles       (chip strip)
//	Footer: generation timestamp
func RenderProjectBriefPDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("P")
	pdf.SetMargins(20, 18, 20)
	pdf.SetAutoPageBreak(true, 18)
	pdf.SetTitle("Project Brief", true)
	pdf.AddPage()

	// Title block
	pdf.SetFont("Helvetica", "B", 22)
	pdf.Cell(0, 12, projectName)
	pdf.Ln(13)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "Project Brief")
	pdf.Ln(8)
	pdf.SetTextColor(0, 0, 0)

	// Summary callout
	if summary := getString(content, "summary", ""); summary != "" {
		drawBriefSummary(pdf, summary)
	}

	// Two-tile KPI strip
	budget, _ := content["budget"].(float64)
	timeline := getString(content, "timeline", "")
	if budget > 0 || timeline != "" {
		drawBriefKPIStrip(pdf, budget, timeline)
	}

	// Goals
	if goals := getStringSlice(content, "goals"); len(goals) > 0 {
		briefHeading(pdf, "Goals")
		drawBriefNumberedList(pdf, goals)
	}

	// Roles
	if roles := getStringSlice(content, "roles"); len(roles) > 0 {
		briefHeading(pdf, "Roles")
		drawBriefChips(pdf, roles)
	}

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func briefHeading(pdf *gofpdf.Fpdf, text string) {
	pdf.Ln(3)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(0, 80, 130)
	pdf.Cell(0, 7, text)
	pdf.Ln(7)
	pdf.SetTextColor(0, 0, 0)
}

func drawBriefSummary(pdf *gofpdf.Fpdf, summary string) {
	pdf.Ln(2)
	startY := pdf.GetY()
	pdf.SetFillColor(239, 246, 255)
	pdf.SetDrawColor(59, 130, 246)
	pdf.SetXY(24, startY+2.5)
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetTextColor(30, 58, 138)
	pdf.CellFormat(80, 4, "SUMMARY", "", 0, "L", false, 0, "")
	pdf.Ln(5)
	pdf.SetX(24)
	pdf.SetFont("Helvetica", "", 11)
	pdf.SetTextColor(17, 24, 39)
	pdf.MultiCell(162, 5.5, summary, "", "L", false)
	endY := pdf.GetY()

	pdf.SetLineWidth(0.5)
	pdf.Rect(20, startY, 170, endY-startY+2, "D")
	pdf.SetLineWidth(0.2)
	pdf.SetXY(20, endY+4)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetDrawColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
}

// drawBriefKPIStrip renders budget and timeline as two side-by-side
// dark KPI tiles. Reuses the budget-tile shape from Project Proposal
// but pairs it with a sibling timeline tile so the two facts share
// visual weight.
func drawBriefKPIStrip(pdf *gofpdf.Fpdf, budget float64, timeline string) {
	startY := pdf.GetY()
	const gap = 4.0
	tileW := (170.0 - gap) / 2
	tileH := 22.0

	// Budget tile
	if budget > 0 {
		drawBriefKPITile(pdf, 20, startY, tileW, tileH,
			"BUDGET", fmt.Sprintf("USD %s", formatMoney(budget)), 16)
	}

	// Timeline tile (shorter font so longer strings fit)
	if timeline != "" {
		drawBriefKPITile(pdf, 20+tileW+gap, startY, tileW, tileH,
			"TIMELINE", timeline, 12)
	}

	pdf.SetXY(20, startY+tileH+5)
}

// drawBriefKPITile draws one dark-filled KPI tile.
func drawBriefKPITile(pdf *gofpdf.Fpdf, x, y, w, h float64, label, value string, valueFontSize float64) {
	pdf.SetFillColor(30, 41, 59)
	pdf.SetDrawColor(30, 41, 59)
	pdf.Rect(x, y, w, h, "F")

	pdf.SetXY(x+3, y+3)
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetTextColor(148, 163, 184)
	pdf.CellFormat(w-6, 4, label, "", 0, "L", false, 0, "")

	pdf.SetXY(x+3, y+9)
	pdf.SetFont("Helvetica", "B", valueFontSize)
	pdf.SetTextColor(255, 255, 255)
	pdf.MultiCell(w-6, valueFontSize*0.45, value, "", "L", false)

	pdf.SetTextColor(0, 0, 0)
	pdf.SetDrawColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
}

func drawBriefNumberedList(pdf *gofpdf.Fpdf, items []string) {
	pdf.SetFont("Helvetica", "", 10)
	for i, item := range items {
		pdf.SetX(20)
		pdf.SetFont("Helvetica", "B", 10)
		pdf.SetTextColor(30, 58, 138)
		pdf.CellFormat(7, 5, fmt.Sprintf("%d.", i+1), "", 0, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 10)
		pdf.SetTextColor(0, 0, 0)
		pdf.MultiCell(0, 5, item, "", "L", false)
	}
	pdf.Ln(2)
}

func drawBriefChips(pdf *gofpdf.Fpdf, items []string) {
	pdf.SetFont("Helvetica", "", 9)
	x := 20.0
	y := pdf.GetY()
	const chipH = 6.0
	const gap = 2.0
	const rightEdge = 190.0
	for _, item := range items {
		w := pdf.GetStringWidth(item) + 6
		if x+w > rightEdge {
			x = 20
			y += chipH + 1.5
		}
		pdf.SetFillColor(226, 232, 240)
		pdf.SetDrawColor(148, 163, 184)
		pdf.RoundedRect(x, y, w, chipH, 1.5, "1234", "FD")
		pdf.SetXY(x+3, y+1)
		pdf.SetTextColor(30, 41, 59)
		pdf.CellFormat(w-6, 4, item, "", 0, "L", false, 0, "")
		x += w + gap
	}
	pdf.SetXY(20, y+chipH+3)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetDrawColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
}
