// SPDX-FileCopyrightText: 2026 James L. Burns and The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// RenderProjectProposalPDF is the bespoke renderer for the Project
// Proposal. Unlike the Charter (formal authorisation) and Business
// Case (analytical), the Proposal is **persuasive** — it has to win
// stakeholder buy-in. The layout reflects that: a prominent executive
// summary callout at the top, a budget KPI tile, team-member name
// chips inline (instead of a dry table), and a bold "Ask" callout at
// the bottom that turns the document into a clear request.
//
// Layout:
//
//	Title bar (portrait A4)
//	Executive Summary callout    (accent-boxed, top of document)
//	Section: Goals               (numbered list, not bulleted)
//	Section: Approach            (FieldText)
//	Section: Team                (chip strip with the proposed team)
//	Section: Timeline            (FieldText)
//	Budget KPI tile              (large dollar amount, right-aligned)
//	"Ask" callout                (bold accent-box, bottom of document)
//	Footer: generation timestamp
func RenderProjectProposalPDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("P")
	pdf.SetMargins(20, 18, 20)
	pdf.SetAutoPageBreak(true, 18)
	pdf.SetTitle("Project Proposal", true)
	pdf.AddPage()

	// Title block
	pdf.SetFont("Helvetica", "B", 22)
	pdf.Cell(0, 12, getString(content, "project_name", projectName))
	pdf.Ln(13)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "Project Proposal")
	pdf.Ln(8)
	pdf.SetTextColor(0, 0, 0)

	// Executive summary — accent callout, top of document
	if summary := getString(content, "executive_summary", ""); summary != "" {
		drawProposalExecSummary(pdf, summary)
	}

	// Goals — numbered list (persuasive, sequential)
	if goals := getStringSlice(content, "goals"); len(goals) > 0 {
		proposalHeading(pdf, "Goals")
		drawProposalNumberedList(pdf, goals)
	}

	// Approach
	if approach := getString(content, "approach", ""); approach != "" {
		proposalHeading(pdf, "Approach")
		pdf.SetFont("Helvetica", "", 10)
		pdf.MultiCell(0, 5, approach, "", "L", false)
		pdf.Ln(2)
	}

	// Team chips
	if team := getStringSlice(content, "team"); len(team) > 0 {
		proposalHeading(pdf, "Proposed Team")
		drawProposalTeamChips(pdf, team)
	}

	// Timeline
	if timeline := getString(content, "timeline", ""); timeline != "" {
		proposalHeading(pdf, "Timeline")
		pdf.SetFont("Helvetica", "", 10)
		pdf.MultiCell(0, 5, timeline, "", "L", false)
		pdf.Ln(2)
	}

	// Budget KPI
	if budget, ok := content["budget_summary"].(float64); ok && budget > 0 {
		drawProposalBudgetTile(pdf, budget)
	}

	// THE ASK — bold accent callout at the bottom
	if ask := getString(content, "ask", ""); ask != "" {
		drawProposalAsk(pdf, ask)
	}

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func proposalHeading(pdf *gofpdf.Fpdf, text string) {
	pdf.Ln(3)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(0, 80, 130)
	pdf.Cell(0, 7, text)
	pdf.Ln(7)
	pdf.SetTextColor(0, 0, 0)
}

// drawProposalExecSummary renders the executive summary as a tinted
// callout box at the top of the document — the first thing the reader
// sees after the title.
func drawProposalExecSummary(pdf *gofpdf.Fpdf, summary string) {
	pdf.Ln(2)
	startY := pdf.GetY()
	pdf.SetFillColor(239, 246, 255)
	pdf.SetDrawColor(59, 130, 246)
	pdf.SetX(20)

	pdf.SetXY(24, startY+2.5)
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetTextColor(30, 58, 138)
	pdf.CellFormat(80, 4, "EXECUTIVE SUMMARY", "", 0, "L", false, 0, "")
	pdf.Ln(5)
	pdf.SetX(24)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(17, 24, 39)
	pdf.MultiCell(162, 5, summary, "", "L", false)
	endY := pdf.GetY()

	pdf.SetLineWidth(0.5)
	pdf.Rect(20, startY, 170, endY-startY+2, "D")
	pdf.SetLineWidth(0.2)
	pdf.SetXY(20, endY+4)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetDrawColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
}

// drawProposalNumberedList renders a string array as a numbered list.
// Numbered (1, 2, 3...) rather than bulleted because the order tends
// to imply priority in a proposal context.
func drawProposalNumberedList(pdf *gofpdf.Fpdf, items []string) {
	pdf.SetFont("Helvetica", "", 10)
	for i, item := range items {
		// Number chip
		numLabel := fmt.Sprintf("%d.", i+1)
		pdf.SetX(20)
		pdf.SetFont("Helvetica", "B", 10)
		pdf.SetTextColor(30, 58, 138)
		pdf.CellFormat(7, 5, numLabel, "", 0, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 10)
		pdf.SetTextColor(0, 0, 0)
		pdf.MultiCell(0, 5, item, "", "L", false)
	}
	pdf.Ln(2)
}

// drawProposalTeamChips renders team member names as wrapping name
// chips — a more persuasive presentation than a dry table when the
// reader doesn't need per-person details (those live in the Team
// Charter document).
func drawProposalTeamChips(pdf *gofpdf.Fpdf, members []string) {
	pdf.SetFont("Helvetica", "", 9)
	x := 20.0
	y := pdf.GetY()
	const chipH = 6.0
	const gap = 2.0
	const rightEdge = 190.0

	for _, name := range members {
		w := pdf.GetStringWidth(name) + 6
		if x+w > rightEdge {
			x = 20
			y += chipH + 1.5
		}
		pdf.SetFillColor(226, 232, 240)
		pdf.SetDrawColor(148, 163, 184)
		pdf.RoundedRect(x, y, w, chipH, 1.5, "1234", "FD")
		pdf.SetXY(x+3, y+1)
		pdf.SetTextColor(30, 41, 59)
		pdf.CellFormat(w-6, 4, name, "", 0, "L", false, 0, "")
		x += w + gap
	}
	pdf.SetXY(20, y+chipH+3)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetDrawColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
}

// drawProposalBudgetTile renders the budget summary as a large
// right-aligned KPI tile so a budget reviewer can scan the page and
// land on the number without reading.
func drawProposalBudgetTile(pdf *gofpdf.Fpdf, budget float64) {
	pdf.Ln(2)
	startY := pdf.GetY()
	tileW := 90.0
	tileH := 18.0
	tileX := 190.0 - tileW

	pdf.SetFillColor(30, 41, 59)
	pdf.SetDrawColor(30, 41, 59)
	pdf.Rect(tileX, startY, tileW, tileH, "F")

	pdf.SetXY(tileX+3, startY+2)
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetTextColor(148, 163, 184)
	pdf.CellFormat(tileW-6, 4, "PROPOSED BUDGET (USD)", "", 0, "L", false, 0, "")

	pdf.SetXY(tileX+3, startY+7)
	pdf.SetFont("Helvetica", "B", 18)
	pdf.SetTextColor(255, 255, 255)
	pdf.CellFormat(tileW-6, 9, formatMoney(budget), "", 0, "L", false, 0, "")

	pdf.SetXY(20, startY+tileH+4)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetDrawColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
}

// drawProposalAsk renders the "what we're asking for" block as a bold
// accent callout. Heavier than the executive summary callout (dark fill
// + light text) because this is the closing CTA — the reader's eye
// should land here last.
func drawProposalAsk(pdf *gofpdf.Fpdf, ask string) {
	pdf.Ln(2)
	startY := pdf.GetY()
	pdf.SetFillColor(30, 58, 138) // dark blue
	pdf.SetDrawColor(30, 58, 138)

	// Header strip
	pdf.Rect(20, startY, 170, 8, "F")
	pdf.SetXY(24, startY+1.5)
	pdf.SetFont("Helvetica", "B", 11)
	pdf.SetTextColor(255, 255, 255)
	pdf.CellFormat(162, 5, "THE ASK", "", 0, "L", false, 0, "")

	// Body with light fill
	pdf.SetFillColor(243, 244, 246)
	pdf.SetXY(24, startY+11)
	pdf.SetFont("Helvetica", "", 11)
	pdf.SetTextColor(17, 24, 39)
	pdf.MultiCell(162, 5.5, ask, "", "L", false)
	endY := pdf.GetY()

	// Outer box wraps both header strip + body
	pdf.SetDrawColor(30, 58, 138)
	pdf.SetLineWidth(0.8)
	pdf.Rect(20, startY, 170, endY-startY+2, "D")
	pdf.SetLineWidth(0.2)

	pdf.SetXY(20, endY+5)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetDrawColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
}
