// SPDX-FileCopyrightText: 2026 James L. Burns and The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"time"

	"github.com/go-pdf/fpdf"
)

// RenderProjectSchedulePDF is the bespoke renderer for the Project
// Schedule document. The document is intentionally thin: the actual
// schedule lives in the linked CPM chart. What this doc adds is the
// formal baseline — a date stamp + supporting notes that lock in a
// reference plan against which actuals are measured.
//
// Layout:
//
//	Title bar (portrait A4)
//	Linked CPM-chart banner
//	Baseline stamp tile (prominent date + days-since computation)
//	Notes section
//	Footer: generation timestamp
//
// Pattern lineage: reuses the linked-chart banner introduced with WBS
// Document and extended with the effective-date row in RACI Document.
// Third application of the pattern, so it's now the established idiom
// for chart-companion docs.
func RenderProjectSchedulePDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("P")
	pdf.SetMargins(20, 18, 20)
	pdf.SetAutoPageBreak(true, 18)
	pdf.SetTitle("Project Schedule", true)
	pdf.AddPage()

	// Title block
	pdf.SetFont("Helvetica", "B", 22)
	pdf.Cell(0, 12, projectName)
	pdf.Ln(13)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "Project Schedule")
	pdf.Ln(8)
	pdf.SetTextColor(0, 0, 0)

	// Linked chart banner
	if ref := getString(content, "schedule_ref", ""); ref != "" {
		drawScheduleChartBanner(pdf, ref)
	}

	// Baseline stamp
	if baseline := getString(content, "baseline_date", ""); baseline != "" {
		drawScheduleBaselineStamp(pdf, baseline)
	} else {
		// No baseline yet — render a soft placeholder so the reader
		// knows a baseline is expected.
		drawScheduleNoBaseline(pdf)
	}

	// Notes
	if notes := getString(content, "notes", ""); notes != "" {
		scheduleHeading(pdf, "Schedule Notes")
		pdf.SetFont("Helvetica", "", 10)
		pdf.MultiCell(0, 5, notes, "", "L", false)
		pdf.Ln(2)
	}

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func scheduleHeading(pdf *fpdf.Fpdf, text string) {
	pdf.Ln(3)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(0, 80, 130)
	pdf.Cell(0, 7, text)
	pdf.Ln(7)
	pdf.SetTextColor(0, 0, 0)
}

// drawScheduleChartBanner is the chart-companion banner adapted for
// CPM-chart linkage. Same shape as WBS Document and RACI Document.
func drawScheduleChartBanner(pdf *fpdf.Fpdf, chartRef string) {
	startY := pdf.GetY()
	pdf.SetFillColor(239, 246, 255)
	pdf.SetDrawColor(59, 130, 246)
	pdf.Rect(20, startY, 170, 10, "FD")
	pdf.SetXY(24, startY+1.5)
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetTextColor(30, 58, 138)
	pdf.CellFormat(40, 4, "LINKED CPM SCHEDULE", "", 0, "L", false, 0, "")
	pdf.SetXY(24, startY+5.5)
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(17, 24, 39)
	pdf.CellFormat(162, 4,
		"Activity network: "+chartRef+"  (see the chart for the diagram; this doc carries the baseline).",
		"", 0, "L", false, 0, "")
	pdf.SetXY(20, startY+12)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetDrawColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
}

// drawScheduleBaselineStamp renders the baseline date as a prominent
// stamp-style tile — visually conveying "this is the authoritative
// baseline against which actuals are measured." The tile reports both
// the date and the elapsed-since-baseline count when the baseline is
// in the past (an "age" indicator for whether the baseline is fresh
// or stale).
func drawScheduleBaselineStamp(pdf *fpdf.Fpdf, baselineStr string) {
	startY := pdf.GetY()
	stampW := 90.0
	stampH := 26.0
	stampX := 20.0

	baseline := parseDate(baselineStr)

	// Background fill + heavy double border for the "stamp" feel.
	pdf.SetFillColor(34, 197, 94) // green-500
	pdf.SetDrawColor(21, 128, 61) // green-700
	pdf.SetLineWidth(1.0)
	pdf.Rect(stampX, startY, stampW, stampH, "FD")
	// Inner double-line for the stamp effect
	pdf.Rect(stampX+1.5, startY+1.5, stampW-3, stampH-3, "D")
	pdf.SetLineWidth(0.2)

	// Header label
	pdf.SetXY(stampX+3, startY+3)
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetTextColor(220, 252, 231) // green-100
	pdf.CellFormat(stampW-6, 4, "BASELINED", "", 0, "L", false, 0, "")

	// Date in large type
	pdf.SetXY(stampX+3, startY+8)
	pdf.SetFont("Helvetica", "B", 18)
	pdf.SetTextColor(255, 255, 255)
	if !baseline.IsZero() {
		pdf.CellFormat(stampW-6, 9, baseline.Format("2006-01-02"), "", 0, "L", false, 0, "")
	} else {
		// Couldn't parse — show the raw string truncated.
		pdf.CellFormat(stampW-6, 9, baselineStr, "", 0, "L", false, 0, "")
	}

	// Age indicator (days since baseline) — only when baseline parses
	// and is in the past.
	if !baseline.IsZero() {
		now := time.Now().UTC()
		days := int(now.Sub(baseline).Hours() / 24)
		ageLabel := ""
		switch {
		case days < 0:
			ageLabel = fmt.Sprintf("baselines in %d day%s", -days, plural(-days))
		case days == 0:
			ageLabel = "baselined today"
		default:
			ageLabel = fmt.Sprintf("baselined %d day%s ago", days, plural(days))
		}
		pdf.SetXY(stampX+3, startY+18.5)
		pdf.SetFont("Helvetica", "I", 8)
		pdf.SetTextColor(220, 252, 231)
		pdf.CellFormat(stampW-6, 4, ageLabel, "", 0, "L", false, 0, "")
	}

	pdf.SetXY(20, startY+stampH+5)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetDrawColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
}

// drawScheduleNoBaseline renders a placeholder tile when no baseline
// date is set. Slate fill (not green) so the reader knows the
// schedule isn't yet locked in.
func drawScheduleNoBaseline(pdf *fpdf.Fpdf) {
	startY := pdf.GetY()
	tileW := 90.0
	tileH := 18.0

	pdf.SetFillColor(241, 245, 249) // slate-100
	pdf.SetDrawColor(148, 163, 184) // slate-400
	pdf.Rect(20, startY, tileW, tileH, "FD")

	pdf.SetXY(23, startY+3)
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetTextColor(71, 85, 105)
	pdf.CellFormat(tileW-6, 4, "BASELINE", "", 0, "L", false, 0, "")
	pdf.SetXY(23, startY+8)
	pdf.SetFont("Helvetica", "I", 10)
	pdf.SetTextColor(100, 116, 139)
	pdf.CellFormat(tileW-6, 6, "Not yet baselined", "", 0, "L", false, 0, "")

	pdf.SetXY(20, startY+tileH+5)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetDrawColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
}

func plural(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}
