// SPDX-FileCopyrightText: 2026 The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"strings"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// RenderProjectOverviewPDF is the bespoke renderer for the Project
// Overview — per the schema: "1-page snapshot: timeline, milestones,
// budget, status, and key roles." The layout is a true one-pager:
// title with a traffic-light status badge in the corner, highlights
// strip prominently below, then a 3-up summary grid of
// milestones / budget / team.
//
// Layout:
//
//	Title bar (portrait A4) with right-aligned status badge
//	Highlights strip       (what should I take away?)
//	3-up summary grid:     Milestones | Budget | Team
//	Footer: generation timestamp
//
// This is the last bespoke renderer: 25/25 effective coverage.
func RenderProjectOverviewPDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("P")
	pdf.SetMargins(20, 18, 20)
	pdf.SetAutoPageBreak(true, 18)
	pdf.SetTitle("Project Overview", true)
	pdf.AddPage()

	// Title block with status badge on the right
	pdf.SetFont("Helvetica", "B", 22)
	pdf.Cell(120, 12, projectName)

	status := getString(content, "status", "")
	if status != "" {
		drawOverviewStatusBadge(pdf, status)
	}
	pdf.Ln(13)

	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "Project Overview")
	pdf.Ln(8)
	pdf.SetTextColor(0, 0, 0)

	// Highlights — prominent strip near the top
	if highlights := getStringSlice(content, "highlights"); len(highlights) > 0 {
		drawOverviewHighlights(pdf, highlights)
	}

	// 3-up summary grid
	milestones := getString(content, "milestones_summary", "")
	budget := getString(content, "budget_summary", "")
	team := getString(content, "team_summary", "")
	if milestones != "" || budget != "" || team != "" {
		drawOverviewGrid(pdf, milestones, budget, team)
	}

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// drawOverviewStatusBadge renders a traffic-light style pill in the
// top-right corner. Same colour vocabulary as Status Report so the
// two docs read consistently.
func drawOverviewStatusBadge(pdf *gofpdf.Fpdf, status string) {
	label, r, g, b := overviewStatusColor(status)
	badgeW := 55.0
	badgeH := 10.0
	x := 190.0 - badgeW
	y := pdf.GetY()

	pdf.SetFillColor(r, g, b)
	pdf.SetDrawColor(r, g, b)
	pdf.RoundedRect(x, y, badgeW, badgeH, 2, "1234", "F")

	pdf.SetXY(x, y+1)
	pdf.SetFont("Helvetica", "B", 8)
	pdf.SetTextColor(255, 255, 255)
	pdf.CellFormat(badgeW, 3.5, "STATUS", "", 0, "C", false, 0, "")

	pdf.SetXY(x, y+5)
	pdf.SetFont("Helvetica", "B", 11)
	pdf.CellFormat(badgeW, 4, label, "", 0, "C", false, 0, "")

	pdf.SetXY(20, y) // restore X so title stays positioned on the left
	pdf.SetTextColor(0, 0, 0)
	pdf.SetDrawColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
}

// overviewStatusColor maps a status string to (label, r, g, b).
// Accepts the canonical green/yellow/red plus common synonyms.
func overviewStatusColor(status string) (string, int, int, int) {
	switch strings.ToLower(strings.TrimSpace(status)) {
	case "green", "on track", "ok", "healthy":
		return "ON TRACK", 21, 128, 61
	case "yellow", "amber", "at risk", "caution":
		return "AT RISK", 180, 83, 9
	case "red", "off track", "blocked", "critical":
		return "OFF TRACK", 185, 28, 28
	case "complete", "done", "closed":
		return "COMPLETE", 71, 85, 105
	default:
		s := strings.ToUpper(strings.TrimSpace(status))
		if s == "" {
			s = "UNKNOWN"
		}
		return s, 100, 116, 139
	}
}

// drawOverviewHighlights renders highlights as a checkmark-prefixed
// list inside a tinted strip. Visually different from the bullet
// pattern so the reader treats them as "things to know" not "things
// to do".
func drawOverviewHighlights(pdf *gofpdf.Fpdf, items []string) {
	pdf.Ln(2)
	startY := pdf.GetY()
	pdf.SetFillColor(254, 252, 232) // amber-50 (warm, attention-grabbing)
	pdf.SetDrawColor(180, 83, 9)    // amber-700

	pdf.SetXY(24, startY+2.5)
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetTextColor(120, 53, 15) // amber-900
	pdf.CellFormat(80, 4, "HIGHLIGHTS", "", 0, "L", false, 0, "")
	pdf.Ln(5)

	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(17, 24, 39)
	for _, h := range items {
		pdf.SetX(24)
		// Checkmark prefix
		pdf.SetTextColor(21, 128, 61)
		pdf.CellFormat(5, 5, "\xe2\x9c\x93", "", 0, "L", false, 0, "")
		pdf.SetTextColor(17, 24, 39)
		pdf.MultiCell(157, 5, h, "", "L", false)
	}
	endY := pdf.GetY()

	pdf.SetLineWidth(0.5)
	pdf.Rect(20, startY, 170, endY-startY+2, "D")
	pdf.SetLineWidth(0.2)
	pdf.SetXY(20, endY+4)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetDrawColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
}

// drawOverviewGrid renders the milestones / budget / team trio as
// three side-by-side cards. Each card has a coloured top edge bar
// (different per category) so the reader can distinguish them at a
// glance.
func drawOverviewGrid(pdf *gofpdf.Fpdf, milestones, budget, team string) {
	startY := pdf.GetY()
	const gap = 4.0
	cardW := (170.0 - 2*gap) / 3

	// Compute card height from the tallest body — gofpdf doesn't give
	// us "the height MultiCell would produce" up-front, so estimate
	// from string widths.
	cardH := overviewCardHeight(pdf, []string{milestones, budget, team}, cardW-4)

	cards := []struct {
		title, body string
		r, g, b     int // top-edge accent
	}{
		{"Milestones", milestones, 59, 130, 246}, // blue
		{"Budget", budget, 21, 128, 61},          // green
		{"Team", team, 180, 83, 9},               // amber
	}

	for i, c := range cards {
		x := 20 + float64(i)*(cardW+gap)

		// Card body
		pdf.SetFillColor(255, 255, 255)
		pdf.SetDrawColor(209, 213, 219)
		pdf.Rect(x, startY, cardW, cardH, "FD")

		// Top accent bar
		pdf.SetFillColor(c.r, c.g, c.b)
		pdf.Rect(x, startY, cardW, 3, "F")

		// Title
		pdf.SetXY(x+3, startY+5)
		pdf.SetFont("Helvetica", "B", 10)
		pdf.SetTextColor(c.r, c.g, c.b)
		pdf.CellFormat(cardW-6, 5, c.title, "", 0, "L", false, 0, "")

		// Body
		pdf.SetXY(x+3, startY+11)
		pdf.SetFont("Helvetica", "", 9)
		pdf.SetTextColor(17, 24, 39)
		body := c.body
		if body == "" {
			body = "(not provided)"
			pdf.SetTextColor(148, 163, 184)
		}
		pdf.MultiCell(cardW-6, 4.5, body, "", "L", false)
	}

	pdf.SetXY(20, startY+cardH+5)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetDrawColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
}

// overviewCardHeight estimates the height needed to hold the tallest
// of the three card bodies. Same approach as RACI Document's
// raciRowHeight: GetStringWidth divided by cell width gives an
// approximate line count.
func overviewCardHeight(pdf *gofpdf.Fpdf, bodies []string, w float64) float64 {
	pdf.SetFont("Helvetica", "", 9)
	maxLines := 3
	for _, body := range bodies {
		if body == "" {
			continue
		}
		lines := int(pdf.GetStringWidth(body)/w) + 1 + strings.Count(body, "\n")
		if lines > maxLines {
			maxLines = lines
		}
	}
	// Title bar (3) + title row (5) + top padding (3) + body lines.
	h := 3.0 + 5 + 3 + float64(maxLines)*4.5 + 3
	if h < 35 {
		h = 35
	}
	return h
}
