// SPDX-FileCopyrightText: 2026 James L. Burns and The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// RenderRACIDocumentPDF is the bespoke renderer for the RACI Chart
// Document. It's a chart-companion doc, so the layout mirrors WBS
// Document's idiom: a linked-chart banner at the top, then
// methodology-specific content beneath. The bespoke twist for RACI is
// a **letter legend** explaining what R / A / C / I each mean — most
// stakeholders see a RACI matrix once a quarter and benefit from the
// reminder. The role-definitions table closes the doc.
//
// Layout:
//
//	Title bar (portrait A4)
//	Linked-chart banner + effective date
//	RACI letter legend (4 coloured chips with full names)
//	Role definitions table:  Role | Definition
//	Footer: generation timestamp
func RenderRACIDocumentPDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("P")
	pdf.SetMargins(20, 18, 20)
	pdf.SetAutoPageBreak(true, 18)
	pdf.SetTitle("RACI Chart Document", true)
	pdf.AddPage()

	// Title block
	pdf.SetFont("Helvetica", "B", 22)
	pdf.Cell(0, 12, projectName)
	pdf.Ln(13)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "RACI Chart Document")
	pdf.Ln(8)
	pdf.SetTextColor(0, 0, 0)

	// Linked chart + effective date
	chartRef := getString(content, "raci_ref", "")
	effectiveDate := getString(content, "effective_date", "")
	if chartRef != "" || effectiveDate != "" {
		drawRACIBanner(pdf, chartRef, effectiveDate)
	}

	// RACI letter legend
	pdf.Ln(2)
	drawRACILegend(pdf)
	pdf.Ln(6)

	// Role definitions
	roles := getObjectSlice(content, "role_definitions")
	if len(roles) == 0 {
		pdf.SetFont("Helvetica", "I", 10)
		pdf.SetTextColor(120, 120, 120)
		pdf.Cell(0, 6, "No role definitions documented yet.")
		pdf.SetTextColor(0, 0, 0)
	} else {
		raciHeading(pdf, "Role Definitions")
		drawRACIRoleTable(pdf, roles)
	}

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func raciHeading(pdf *gofpdf.Fpdf, text string) {
	pdf.Ln(3)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(0, 80, 130)
	pdf.Cell(0, 7, text)
	pdf.Ln(7)
	pdf.SetTextColor(0, 0, 0)
}

// drawRACIBanner is the chart-companion banner adapted from WBS
// Document, with a second row for effective date. Tinted strip,
// label-and-value layout.
func drawRACIBanner(pdf *gofpdf.Fpdf, chartRef, effectiveDate string) {
	height := 10.0
	if effectiveDate != "" && chartRef != "" {
		height = 14.0
	}
	startY := pdf.GetY()
	pdf.SetFillColor(239, 246, 255)
	pdf.SetDrawColor(59, 130, 246)
	pdf.Rect(20, startY, 170, height, "FD")

	yCursor := startY + 1.5
	if chartRef != "" {
		pdf.SetXY(24, yCursor)
		pdf.SetFont("Helvetica", "B", 9)
		pdf.SetTextColor(30, 58, 138)
		pdf.CellFormat(40, 4, "LINKED RACI MATRIX", "", 0, "L", false, 0, "")
		pdf.SetXY(24, yCursor+4)
		pdf.SetFont("Helvetica", "", 9)
		pdf.SetTextColor(17, 24, 39)
		pdf.CellFormat(162, 4, "Visual structure: "+chartRef, "", 0, "L", false, 0, "")
		yCursor += 8.5
	}
	if effectiveDate != "" {
		pdf.SetXY(24, yCursor)
		pdf.SetFont("Helvetica", "B", 9)
		pdf.SetTextColor(30, 58, 138)
		pdf.CellFormat(40, 4, "EFFECTIVE", "", 0, "L", false, 0, "")
		pdf.SetXY(60, yCursor)
		pdf.SetFont("Helvetica", "", 9)
		pdf.SetTextColor(17, 24, 39)
		pdf.CellFormat(125, 4, effectiveDate, "", 0, "L", false, 0, "")
	}

	pdf.SetXY(20, startY+height+2)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetDrawColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
}

// drawRACILegend renders the four RACI letters as colour-coded chips
// with their full meanings. Colour vocabulary mirrors the RACI matrix
// chart's own legend so the doc and the chart use the same visual
// language.
func drawRACILegend(pdf *gofpdf.Fpdf) {
	letters := []struct {
		letter, label string
		r, g, b       int
	}{
		{"R", "Responsible (does the work)", 21, 128, 61},    // green
		{"A", "Accountable (owns the outcome)", 185, 28, 28}, // red
		{"C", "Consulted (input before)", 180, 83, 9},        // amber
		{"I", "Informed (notified after)", 14, 116, 144},     // cyan
	}

	startY := pdf.GetY()
	colW := 40.0
	chipW := 7.0
	for i, l := range letters {
		x := 20 + float64(i)*colW

		// Letter chip
		pdf.SetFillColor(l.r, l.g, l.b)
		pdf.SetDrawColor(l.r, l.g, l.b)
		pdf.RoundedRect(x, startY, chipW, 7, 1.2, "1234", "F")
		pdf.SetXY(x, startY+1.2)
		pdf.SetFont("Helvetica", "B", 11)
		pdf.SetTextColor(255, 255, 255)
		pdf.CellFormat(chipW, 4.5, l.letter, "", 0, "C", false, 0, "")

		// Label to the right of the chip
		pdf.SetXY(x+chipW+1.5, startY+1)
		pdf.SetFont("Helvetica", "", 7.5)
		pdf.SetTextColor(60, 60, 60)
		pdf.MultiCell(colW-chipW-2, 3, l.label, "", "L", false)
	}

	pdf.SetXY(20, startY+8)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
	pdf.SetDrawColor(0, 0, 0)
}

// drawRACIRoleTable renders the role-definitions table. Two columns
// (Role | Definition) so the heading bar and body have a clean
// alignment with the rest of the page.
func drawRACIRoleTable(pdf *gofpdf.Fpdf, roles []map[string]interface{}) {
	cols := []struct {
		header string
		w      float64
	}{
		{"Role", 55},
		{"Definition", 115},
	}

	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetFillColor(30, 41, 59)
	pdf.SetTextColor(241, 245, 249)
	pdf.SetDrawColor(100, 116, 139)
	for _, c := range cols {
		pdf.CellFormat(c.w, 7, c.header, "1", 0, "L", true, 0, "")
	}
	pdf.Ln(-1)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFont("Helvetica", "", 9)

	for i, r := range roles {
		role := getStringRACI(r, "role")
		def := getStringRACI(r, "definition")

		// Row fill (alternating)
		if i%2 == 0 {
			pdf.SetFillColor(248, 250, 252)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}

		// Both cells need the same height; measure the taller and
		// then fill with empty cells before re-positioning text.
		startX := pdf.GetX()
		startY := pdf.GetY()
		rowH := raciRowHeight(pdf, def, cols[1].w-3)

		pdf.CellFormat(cols[0].w, rowH, "", "1", 0, "L", true, 0, "")
		pdf.CellFormat(cols[1].w, rowH, "", "1", 0, "L", true, 0, "")

		// Now write the actual text.
		pdf.SetXY(startX+1.5, startY+1)
		pdf.SetFont("Helvetica", "B", 9)
		pdf.MultiCell(cols[0].w-3, 4.5, role, "", "L", false)

		pdf.SetXY(startX+cols[0].w+1.5, startY+1)
		pdf.SetFont("Helvetica", "", 9)
		pdf.MultiCell(cols[1].w-3, 4.5, def, "", "L", false)

		pdf.SetXY(startX, startY+rowH)
	}
}

// raciRowHeight estimates the cell height needed to hold `text`
// inside a cell `w` wide at 9pt, with 4.5mm line height. The 0.5
// minimum char width is a coarse approximation that errs on the side
// of more height (avoiding text clipping at row borders).
func raciRowHeight(pdf *gofpdf.Fpdf, text string, w float64) float64 {
	if text == "" {
		return 6
	}
	// Use gofpdf's own string-width to estimate wrapped lines.
	pdf.SetFont("Helvetica", "", 9)
	textW := pdf.GetStringWidth(text)
	lines := int(textW/w) + 1
	h := float64(lines)*4.5 + 2
	if h < 6 {
		h = 6
	}
	return h
}

func getStringRACI(m map[string]interface{}, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}
