// SPDX-FileCopyrightText: 2026 The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"

	"pmforge/internal/charts/pdfrender"
)

// ReportSection is one entry in a combined report. The caller passes
// these in the order they should appear in the final PDF.
type ReportSection struct {
	DocumentID  string `json:"document_id"`
	Title       string `json:"title"`       // display title; falls back to the doc's own title
	Description string `json:"description"` // optional one-line intro under the heading
}

// ReportSpec is the input for BuildCombinedReport.
//
// ResolvedCharts, when populated, is consulted whenever
// renderSectionBody encounters a FieldChartRef value. The map is
// keyed by chart ID; missing entries fall back to a text line.
// Pre-resolution keeps this package free of database dependencies.
type ReportSpec struct {
	ReportTitle    string                   `json:"report_title"`
	Subtitle       string                   `json:"subtitle"`
	Author         string                   `json:"author"`
	ProjectName    string                   `json:"project_name"`
	Sections       []ReportSection          `json:"sections"`
	ResolvedCharts map[string]ResolvedChart `json:"-"`
}

// ResolvedChart carries the data BuildCombinedReport needs to embed
// a chart visualisation: the kind (so the pdfrender dispatcher can
// pick the right engine), the title (drawn above the chart), and
// the raw db.charts.data JSON (passed to the engine renderer).
type ResolvedChart struct {
	Kind  string
	Title string
	Data  string
}

// ResolvedSection is a section plus its resolved document content,
// ready for rendering. Built by the caller because this package
// shouldn't touch the database directly.
type ResolvedSection struct {
	Section ReportSection
	Kind    Kind
	Content string // raw JSON content
	Version int
	Status  string
}

// BuildCombinedReport produces a single PDF that consists of:
//
//	Page 1                cover (report title, subtitle, author,
//	                      project name, generation timestamp)
//	Page 2                table of contents
//	Pages 3..N            one section per ResolvedSection, each
//	                      starting with a heading and the section
//	                      description, followed by the document's
//	                      content rendered via the existing kind-
//	                      specific or generic renderer (we call
//	                      Render() with a small adapter).
//
// Charts are referenced only by ID in this V1 of the report
// builder; embedding chart visualisations as raster images is a
// follow-up (see README V2 TODOs).
func BuildCombinedReport(spec ReportSpec, sections []ResolvedSection) ([]byte, error) {
	pdf := newDocPDF("P")
	pdf.SetMargins(20, 18, 20)
	pdf.SetAutoPageBreak(true, 18)
	pdf.SetTitle(spec.ReportTitle, true)
	pdf.SetAuthor(spec.Author, true)

	// --- Cover page ---
	pdf.AddPage()
	pdf.SetFont("Helvetica", "B", 28)
	pdf.SetY(60)
	pdf.MultiCell(0, 12, spec.ReportTitle, "", "C", false)
	if spec.Subtitle != "" {
		pdf.SetFont("Helvetica", "", 14)
		pdf.SetTextColor(110, 110, 110)
		pdf.Ln(4)
		pdf.MultiCell(0, 7, spec.Subtitle, "", "C", false)
		pdf.SetTextColor(0, 0, 0)
	}
	pdf.Ln(12)
	pdf.SetFont("Helvetica", "", 11)
	if spec.ProjectName != "" {
		pdf.MultiCell(0, 6, "Project: "+spec.ProjectName, "", "C", false)
	}
	if spec.Author != "" {
		pdf.MultiCell(0, 6, "Author: "+spec.Author, "", "C", false)
	}
	pdf.SetY(-30)
	pdf.SetFont("Helvetica", "I", 9)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		"Generated by PMForge at "+time.Now().UTC().Format(time.RFC3339Nano),
		"", 0, "C", false, 0, "")
	pdf.SetTextColor(0, 0, 0)

	// --- Table of contents ---
	pdf.AddPage()
	pdf.SetFont("Helvetica", "B", 18)
	pdf.Cell(0, 10, "Contents")
	pdf.Ln(12)
	pdf.SetFont("Helvetica", "", 11)
	for i, s := range sections {
		title := s.Section.Title
		if title == "" {
			title = "Section " + itoa(i+1)
		}
		pdf.CellFormat(10, 7, itoa(i+1)+".", "", 0, "L", false, 0, "")
		pdf.CellFormat(0, 7, title, "", 1, "L", false, 0, "")
	}

	// --- Sections ---
	for i, s := range sections {
		pdf.AddPage()
		pdf.SetFont("Helvetica", "B", 16)
		title := s.Section.Title
		if title == "" {
			title = "Section " + itoa(i+1)
		}
		pdf.Cell(0, 10, itoa(i+1)+". "+title)
		pdf.Ln(12)

		if s.Section.Description != "" {
			pdf.SetFont("Helvetica", "I", 10)
			pdf.SetTextColor(110, 110, 110)
			pdf.MultiCell(0, 5, s.Section.Description, "", "L", false)
			pdf.SetTextColor(0, 0, 0)
			pdf.Ln(2)
		}

		// Render the document body inline by reusing the per-kind
		// PDF renderer's logic. Rather than nest PDFs (gofpdf has
		// no embed-PDF support), we replay the generic field-walking
		// directly here, with reduced heading sizes so it nests
		// visually inside the report's outer structure.
		chartRefs, err := renderSectionBody(pdf, s)
		if err != nil {
			return nil, fmt.Errorf("render section %s: %w", s.Section.DocumentID, err)
		}

		// Embed any referenced charts on their own pages so they get
		// the full body width. Each chart gets a heading describing
		// the field it came from (e.g. "Linked WBS").
		for _, ref := range chartRefs {
			rc, ok := spec.ResolvedCharts[ref.chartID]
			if !ok {
				continue // chart not resolvable; the inline KV line already noted the ID
			}
			pdf.AddPage()
			// gofpdf v1.16.2 has no GetPageHeight; GetPageSize returns
			// (width, height).
			_, pageH := pdf.GetPageSize()
			frame := pdfrender.Frame{
				X: 20, Y: 20,
				W: 170, // A4 portrait body width
				H: pageH - 40,
			}
			if err := pdfrender.RenderChartToPDF(pdf, rc.Kind, rc.Data, ref.label, frame); err != nil {
				// A render failure on one chart shouldn't kill the
				// whole report — drop in a placeholder and keep going.
				drawChartFallback(pdf, frame, rc, err.Error())
			}
		}
	}

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// chartRefMention is one chart_ref field BuildCombinedReport
// discovered while walking a section. The caller (BuildCombinedReport)
// embeds each referenced chart on its own page after the section's
// text content.
type chartRefMention struct {
	label   string // the document field's display label, e.g. "Linked WBS"
	chartID string // the user-selected chart ID
}

// renderSectionBody walks a document's fields and emits them inline
// in the combined report. It mirrors renderGenericPDF in charter.go
// but uses smaller heading sizes so the section reads as a
// subordinate part of the larger report.
//
// Returns the list of chart_ref field values encountered, in walk
// order, so the caller can embed the corresponding chart
// visualisations on their own pages.
func renderSectionBody(pdf *gofpdf.Fpdf, s ResolvedSection) ([]chartRefMention, error) {
	def, ok := Get(s.Kind)
	if !ok {
		return nil, fmt.Errorf("unknown kind %q", s.Kind)
	}
	var content map[string]interface{}
	if s.Content != "" {
		if err := json.Unmarshal([]byte(s.Content), &content); err != nil {
			return nil, fmt.Errorf("invalid content JSON: %w", err)
		}
	}

	// Kind name + version/status badge.
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(110, 110, 110)
	pdf.CellFormat(0, 5,
		def.Name+"  ·  v"+itoa(s.Version)+"  ·  "+s.Status,
		"", 1, "L", false, 0, "")
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(3)

	var chartRefs []chartRefMention
	for _, f := range EffectiveFields(s.Kind) {
		v, present := content[f.Key]
		if !present {
			continue
		}
		switch f.Type {
		case FieldStringArr:
			arr := toStringSlice(v)
			if len(arr) == 0 {
				continue
			}
			writeSubHeading(pdf, f.Label)
			pdf.SetFont("Helvetica", "", 9)
			for _, item := range arr {
				pdf.Cell(4, 4.5, "•")
				pdf.MultiCell(0, 4.5, item, "", "L", false)
			}
			pdf.Ln(1)
		case FieldObjectArr:
			objs := toObjectSlice(v)
			if len(objs) == 0 {
				continue
			}
			writeSubHeading(pdf, f.Label)
			renderObjectArray(pdf, f, objs)
		case FieldText:
			body := toString(v)
			if body == "" {
				continue
			}
			writeSubHeading(pdf, f.Label)
			pdf.SetFont("Helvetica", "", 9)
			pdf.MultiCell(0, 4.5, body, "", "L", false)
			pdf.Ln(1)
		case FieldNumber:
			if n, ok := v.(float64); ok && n != 0 {
				writeKVCompact(pdf, f.Label, fmt.Sprintf("%.2f", n))
			}
		case FieldBool:
			if b, ok := v.(bool); ok {
				writeKVCompact(pdf, f.Label, fmt.Sprintf("%t", b))
			}
		case FieldChartRef:
			if id := toString(v); id != "" {
				writeKVCompact(pdf, f.Label, "(see attached "+id+")")
				chartRefs = append(chartRefs, chartRefMention{
					label:   f.Label,
					chartID: id,
				})
			}
		default:
			if str := toString(v); str != "" {
				writeKVCompact(pdf, f.Label, str)
			}
		}
	}
	return chartRefs, nil
}

// drawChartFallback paints a "chart not available" placeholder when
// pdfrender returns an error or the resolved chart is missing.
func drawChartFallback(pdf *gofpdf.Fpdf, frame pdfrender.Frame, rc ResolvedChart, reason string) {
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetTextColor(0, 80, 130)
	pdf.SetXY(frame.X, frame.Y)
	pdf.CellFormat(frame.W, 8, rc.Title, "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "I", 9)
	pdf.SetTextColor(180, 100, 60)
	pdf.SetXY(frame.X, frame.Y+frame.H/2-3)
	pdf.CellFormat(frame.W, 6, "Chart preview unavailable: "+reason, "", 0, "C", false, 0, "")
	pdf.SetTextColor(0, 0, 0)
}

func writeSubHeading(pdf *gofpdf.Fpdf, label string) {
	pdf.Ln(2)
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetTextColor(0, 80, 130)
	pdf.Cell(0, 6, label)
	pdf.Ln(6)
	pdf.SetTextColor(0, 0, 0)
}

func writeKVCompact(pdf *gofpdf.Fpdf, k, v string) {
	pdf.SetFont("Helvetica", "B", 9)
	pdf.CellFormat(36, 4.5, k+":", "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "", 9)
	pdf.MultiCell(0, 4.5, v, "", "L", false)
}

// itoa avoids dragging in strconv for the two integer formats we use.
func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	neg := n < 0
	if neg {
		n = -n
	}
	var buf [12]byte
	i := len(buf)
	for n > 0 {
		i--
		buf[i] = byte('0' + n%10)
		n /= 10
	}
	if neg {
		i--
		buf[i] = '-'
	}
	return string(buf[i:])
}
