// SPDX-FileCopyrightText: 2026 James L. Burns and The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"sort"
	"time"

	"github.com/go-pdf/fpdf"
)

// RenderRequirementsPDF is the bespoke renderer for the Requirements
// Document. Requirements are table-heavy, and the canonical layout
// groups them by type (functional, non-functional, business, technical)
// then sorts by priority within each group so reviewers can scan the
// highest-priority items first.
//
// Layout:
//
//	Title bar (landscape A4)
//	Priority legend chips
//	Requirements table:
//	  Req ID | Type | Priority | Source | Description
//	  grouped by type, sorted high → low within each group
//	Footer: generation timestamp
func RenderRequirementsPDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("L") // landscape for the wide table
	pdf.SetMargins(15, 15, 15)
	pdf.SetAutoPageBreak(true, 15)
	pdf.SetTitle("Requirements Document", true)
	pdf.AddPage()

	// Title
	pdf.SetFont("Helvetica", "B", 20)
	pdf.Cell(0, 11, projectName)
	pdf.Ln(11)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "Requirements Document")
	pdf.Ln(8)
	pdf.SetTextColor(0, 0, 0)

	// Priority legend
	drawReqLegend(pdf)
	pdf.Ln(8)

	// Pull, normalise, and sort requirements.
	reqs := normaliseRequirements(getObjectSlice(content, "requirements"))
	if len(reqs) == 0 {
		pdf.SetFont("Helvetica", "I", 10)
		pdf.SetTextColor(120, 120, 120)
		pdf.Cell(0, 6, "No requirements recorded yet.")
		pdf.SetTextColor(0, 0, 0)
	} else {
		// Sort: type asc (canonical order), then priority desc within type.
		sort.SliceStable(reqs, func(i, j int) bool {
			ti, tj := reqTypeOrder(reqs[i].Type), reqTypeOrder(reqs[j].Type)
			if ti != tj {
				return ti < tj
			}
			return reqPriorityOrder(reqs[i].Priority) < reqPriorityOrder(reqs[j].Priority)
		})
		drawReqTable(pdf, reqs)
	}

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// req is the typed view of one requirements row.
type req struct {
	ID          string
	Description string
	Type        string
	Priority    string
	Source      string
}

func normaliseRequirements(raw []map[string]interface{}) []req {
	out := make([]req, 0, len(raw))
	for _, r := range raw {
		out = append(out, req{
			ID:          getStringReq(r, "id"),
			Description: getStringReq(r, "description"),
			Type:        getStringReq(r, "type"),
			Priority:    getStringReq(r, "priority"),
			Source:      getStringReq(r, "source"),
		})
	}
	return out
}

// reqTypeOrder maps requirement type to a canonical display order.
// Unknown types sort last.
func reqTypeOrder(t string) int {
	switch t {
	case "business":
		return 0
	case "functional":
		return 1
	case "non-functional":
		return 2
	case "technical":
		return 3
	default:
		return 4
	}
}

// reqPriorityOrder maps priority string to ascending sort order
// (lower = higher priority in the UI).
func reqPriorityOrder(p string) int {
	switch p {
	case "critical", "high":
		return 0
	case "medium":
		return 1
	case "low":
		return 2
	default:
		return 3
	}
}

// drawReqLegend renders priority-band chips.
func drawReqLegend(pdf *fpdf.Fpdf) {
	pdf.SetFont("Helvetica", "B", 8)
	bands := []struct {
		label   string
		r, g, b int
	}{
		{"Critical / High", 185, 28, 28},
		{"Medium", 180, 83, 9},
		{"Low", 14, 116, 144},
		{"Other", 71, 85, 105},
	}
	x := pdf.GetX()
	y := pdf.GetY()
	for _, b := range bands {
		pdf.SetFillColor(b.r, b.g, b.b)
		pdf.SetDrawColor(b.r, b.g, b.b)
		pdf.RoundedRect(x, y, 44, 7, 2, "1234", "F")
		pdf.SetTextColor(255, 255, 255)
		pdf.SetXY(x+2, y+1.5)
		pdf.CellFormat(40, 4, b.label, "", 0, "C", false, 0, "")
		x += 47
	}
	pdf.SetXY(15, y+7)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
	pdf.SetDrawColor(0, 0, 0)
}

// drawReqTable emits requirements as a table with priority-coloured ID
// cells and type-group header rows.
func drawReqTable(pdf *fpdf.Fpdf, reqs []req) {
	// Column widths (mm) — landscape A4 body ≈ 267mm.
	cols := []struct {
		header string
		w      float64
		align  string
	}{
		{"Req ID", 22, "L"},
		{"Type", 30, "L"},
		{"Priority", 24, "L"},
		{"Source / Stakeholder", 45, "L"},
		{"Description", 146, "L"},
	}

	// Table header
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(30, 41, 59)
	pdf.SetTextColor(241, 245, 249)
	pdf.SetDrawColor(100, 116, 139)
	for _, c := range cols {
		pdf.CellFormat(c.w, 7, c.header, "1", 0, c.align, true, 0, "")
	}
	pdf.Ln(-1)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFont("Helvetica", "", 8)

	prevType := ""
	for _, r := range reqs {
		// Type-group header row
		if r.Type != prevType {
			prevType = r.Type
			label := r.Type
			if label == "" {
				label = "Other"
			}
			pdf.SetFont("Helvetica", "B", 8)
			pdf.SetFillColor(226, 232, 240)
			total := 0.0
			for _, c := range cols {
				total += c.w
			}
			pdf.CellFormat(total, 5, "  "+label, "LR", 0, "L", true, 0, "")
			pdf.Ln(-1)
			pdf.SetFont("Helvetica", "", 8)
		}

		rr, gg, bb := reqPriorityColor(r.Priority)
		pdf.SetFillColor(rr, gg, bb)
		pdf.SetTextColor(255, 255, 255)
		pdf.CellFormat(cols[0].w, 6, r.ID, "1", 0, "L", true, 0, "")
		pdf.SetTextColor(0, 0, 0)
		pdf.SetFillColor(255, 255, 255)
		pdf.CellFormat(cols[1].w, 6, truncReq(r.Type, 24), "1", 0, "L", false, 0, "")
		pdf.CellFormat(cols[2].w, 6, truncReq(r.Priority, 18), "1", 0, "L", false, 0, "")
		pdf.CellFormat(cols[3].w, 6, truncReq(r.Source, 38), "1", 0, "L", false, 0, "")
		pdf.CellFormat(cols[4].w, 6, truncReq(r.Description, 120), "1", 0, "L", false, 0, "")
		pdf.Ln(-1)
	}
}

func reqPriorityColor(p string) (int, int, int) {
	switch p {
	case "critical":
		return 127, 29, 29
	case "high":
		return 185, 28, 28
	case "medium":
		return 180, 83, 9
	case "low":
		return 14, 116, 144
	default:
		return 71, 85, 105
	}
}

func getStringReq(m map[string]interface{}, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}

func truncReq(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "\xe2\x80\xa6" // …
}
