// SPDX-FileCopyrightText: 2026 James L. Burns and The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"sort"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// RenderRiskRegisterPDF is the second reference bespoke renderer
// (after Status Report), exercising the pattern beyond bulleted
// lists. The Risk Register's content has a single field of interest
// — `risks`, an object array — but the canonical print layout is
// a sorted table coloured by risk score (probability × impact), so
// the renderer is genuinely bespoke rather than generic-walker.
//
// Layout:
//
//	Page 1 title block
//	Heat-map legend (5 chips: Low / Medium / High / Severe / Extreme)
//	Risks table:
//	  ID | Description | Owner | P | I | Score | Status | Mitigation
//	  rows sorted by score descending
//	  each row's first cell tinted by its risk band
//	Footer: timestamp + PMForge version
func RenderRiskRegisterPDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("L") // landscape for the wide table
	pdf.SetMargins(15, 15, 15)
	pdf.SetAutoPageBreak(true, 15)
	pdf.SetTitle("Risk Register", true)
	pdf.AddPage()

	// Title
	pdf.SetFont("Helvetica", "B", 20)
	pdf.Cell(0, 11, projectName)
	pdf.Ln(11)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "Risk Register")
	pdf.Ln(8)
	pdf.SetTextColor(0, 0, 0)

	// Legend
	drawRiskLegend(pdf)
	pdf.Ln(8)

	// Pull and sort risks.
	risks := normaliseRisks(getObjectSliceR(content, "risks"))
	sort.SliceStable(risks, func(i, j int) bool {
		return risks[i].Score > risks[j].Score
	})

	if len(risks) == 0 {
		pdf.SetFont("Helvetica", "I", 10)
		pdf.SetTextColor(120, 120, 120)
		pdf.Cell(0, 6, "No risks recorded yet.")
		pdf.SetTextColor(0, 0, 0)
	} else {
		drawRiskTable(pdf, risks)
	}

	DrawCompactSignatureBox(pdf, projectName, time.Now().Format("2006-01-02"))

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// risk is the typed view of one row in the risks object array.
type risk struct {
	ID          string
	Description string
	Owner       string
	Status      string
	Mitigation  string
	Probability float64 // 1..5
	Impact      float64 // 1..5
	Score       float64 // P × I, computed
}

// normaliseRisks turns the raw map[string]interface{} array into a
// typed slice with the computed Score field populated.
func normaliseRisks(raw []map[string]interface{}) []risk {
	out := make([]risk, 0, len(raw))
	for _, r := range raw {
		x := risk{
			ID:          getStringR(r, "id"),
			Description: getStringR(r, "description"),
			Owner:       getStringR(r, "owner"),
			Status:      getStringR(r, "status"),
			Mitigation:  getStringR(r, "mitigation"),
			Probability: getFloatR(r, "probability"),
			Impact:      getFloatR(r, "impact"),
		}
		x.Score = x.Probability * x.Impact
		out = append(out, x)
	}
	return out
}

// drawRiskLegend renders the five risk-band chips. The bands match
// the score ranges drawRiskTable uses for cell tinting:
//
//	1..3   Low       slate
//	4..6   Medium    cyan
//	7..12  High      amber
//	13..19 Severe    red
//	20..25 Extreme   dark red
func drawRiskLegend(pdf *gofpdf.Fpdf) {
	pdf.SetFont("Helvetica", "B", 8)
	bands := []struct {
		label   string
		score   string
		r, g, b int
	}{
		{"Low", "1–3", 71, 85, 105},
		{"Medium", "4–6", 14, 116, 144},
		{"High", "7–12", 180, 83, 9},
		{"Severe", "13–19", 185, 28, 28},
		{"Extreme", "20–25", 127, 29, 29},
	}
	x := pdf.GetX()
	y := pdf.GetY()
	for _, b := range bands {
		pdf.SetFillColor(b.r, b.g, b.b)
		pdf.SetDrawColor(b.r, b.g, b.b)
		pdf.RoundedRect(x, y, 50, 9, 2, "1234", "F")
		pdf.SetTextColor(255, 255, 255)
		pdf.SetXY(x+2, y+1)
		pdf.CellFormat(46, 3.5, b.label, "", 0, "L", false, 0, "")
		pdf.SetXY(x+2, y+5)
		pdf.CellFormat(46, 3.5, "Score "+b.score, "", 0, "L", false, 0, "")
		x += 53
	}
	pdf.SetXY(15, y+9)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
	pdf.SetDrawColor(0, 0, 0)
}

// drawRiskTable emits the risks as a table with the first column
// tinted by risk band.
func drawRiskTable(pdf *gofpdf.Fpdf, risks []risk) {
	// Column widths (mm) — landscape A4 body is ~267mm.
	cols := []struct {
		header string
		w      float64
	}{
		{"ID", 22},
		{"Description", 70},
		{"Owner", 30},
		{"P", 10},
		{"I", 10},
		{"Score", 16},
		{"Status", 25},
		{"Mitigation", 84},
	}

	// Header
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(30, 41, 59)
	pdf.SetTextColor(241, 245, 249)
	pdf.SetDrawColor(100, 116, 139)
	for _, c := range cols {
		pdf.CellFormat(c.w, 7, c.header, "1", 0, "L", true, 0, "")
	}
	pdf.Ln(-1)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFont("Helvetica", "", 8)

	// Body
	for _, r := range risks {
		rr, gg, bb := riskColor(r.Score)
		pdf.SetFillColor(rr, gg, bb)
		pdf.SetTextColor(255, 255, 255)
		pdf.CellFormat(cols[0].w, 6, r.ID, "1", 0, "L", true, 0, "")
		pdf.SetTextColor(0, 0, 0)
		pdf.SetFillColor(255, 255, 255)
		pdf.CellFormat(cols[1].w, 6, truncR(r.Description, 60), "1", 0, "L", false, 0, "")
		pdf.CellFormat(cols[2].w, 6, truncR(r.Owner, 25), "1", 0, "L", false, 0, "")
		pdf.CellFormat(cols[3].w, 6, fmt.Sprintf("%.0f", r.Probability), "1", 0, "C", false, 0, "")
		pdf.CellFormat(cols[4].w, 6, fmt.Sprintf("%.0f", r.Impact), "1", 0, "C", false, 0, "")
		pdf.CellFormat(cols[5].w, 6, fmt.Sprintf("%.0f", r.Score), "1", 0, "C", false, 0, "")
		pdf.CellFormat(cols[6].w, 6, truncR(r.Status, 22), "1", 0, "L", false, 0, "")
		pdf.CellFormat(cols[7].w, 6, truncR(r.Mitigation, 72), "1", 0, "L", false, 0, "")
		pdf.Ln(-1)
	}
}

// riskColor maps a numeric score 0..25 to a band RGB triple.
func riskColor(score float64) (int, int, int) {
	switch {
	case score >= 20:
		return 127, 29, 29 // extreme
	case score >= 13:
		return 185, 28, 28 // severe
	case score >= 7:
		return 180, 83, 9 // high
	case score >= 4:
		return 14, 116, 144 // medium
	default:
		return 71, 85, 105 // low
	}
}

// Local helpers — same pattern Status Report follows.

func getStringR(m map[string]interface{}, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}

func getFloatR(m map[string]interface{}, key string) float64 {
	if v, ok := m[key].(float64); ok {
		return v
	}
	return 0
}

func getObjectSliceR(m map[string]interface{}, key string) []map[string]interface{} {
	v, ok := m[key].([]interface{})
	if !ok {
		return nil
	}
	out := make([]map[string]interface{}, 0, len(v))
	for _, x := range v {
		if obj, ok := x.(map[string]interface{}); ok {
			out = append(out, obj)
		}
	}
	return out
}

func truncR(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "…"
}
