// SPDX-FileCopyrightText: 2026 James L. Burns and The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// RenderScopeStatementPDF is the bespoke renderer for the Scope
// Statement. The document is prose-heavy — it defines exactly what the
// project will and will not deliver — so the layout follows the Charter
// pattern: portrait A4, section headings + body text + bulleted lists.
//
// Layout:
//
//	Title bar:           Project name + "Scope Statement"
//	Section: Scope Description   (FieldText)
//	Section: Deliverables        (StringArr, bulleted)
//	Section: Acceptance Criteria (StringArr, bulleted, boxed)
//	Section: Exclusions          (StringArr, bulleted)
//	Section: Constraints         (StringArr, bulleted)
//	Section: Assumptions         (StringArr, bulleted)
//	Footer:                      generation timestamp
func RenderScopeStatementPDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("P")
	pdf.SetMargins(20, 18, 20)
	pdf.SetAutoPageBreak(true, 18)
	pdf.SetTitle("Scope Statement", true)
	pdf.AddPage()

	// Title block
	pdf.SetFont("Helvetica", "B", 22)
	pdf.Cell(0, 12, getString(content, "project_name", projectName))
	pdf.Ln(13)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "Scope Statement")
	pdf.Ln(8)
	pdf.SetTextColor(0, 0, 0)

	scopeSectionText(pdf, "Scope Description", getString(content, "scope_description", ""))
	scopeBullets(pdf, "Deliverables", getStringSlice(content, "deliverables"))
	scopeAcceptanceCriteria(pdf, getStringSlice(content, "acceptance_criteria"))
	scopeBullets(pdf, "Exclusions", getStringSlice(content, "exclusions"))
	scopeBullets(pdf, "Constraints", getStringSlice(content, "constraints"))
	scopeBullets(pdf, "Assumptions", getStringSlice(content, "assumptions"))

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func scopeHeading(pdf *gofpdf.Fpdf, text string) {
	pdf.Ln(3)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(0, 80, 130)
	pdf.Cell(0, 7, text)
	pdf.Ln(7)
	pdf.SetTextColor(0, 0, 0)
}

func scopeSectionText(pdf *gofpdf.Fpdf, heading, body string) {
	if body == "" {
		return
	}
	scopeHeading(pdf, heading)
	pdf.SetFont("Helvetica", "", 10)
	pdf.MultiCell(0, 5, body, "", "L", false)
	pdf.Ln(2)
}

func scopeBullets(pdf *gofpdf.Fpdf, heading string, items []string) {
	if len(items) == 0 {
		return
	}
	scopeHeading(pdf, heading)
	pdf.SetFont("Helvetica", "", 10)
	for _, it := range items {
		pdf.Cell(5, 5, "\xe2\x80\xa2")
		pdf.MultiCell(0, 5, it, "", "L", false)
	}
	pdf.Ln(2)
}

// scopeAcceptanceCriteria renders acceptance criteria with a teal left
// rule to visually distinguish them as the formal verification gate.
func scopeAcceptanceCriteria(pdf *gofpdf.Fpdf, items []string) {
	if len(items) == 0 {
		return
	}
	scopeHeading(pdf, "Acceptance Criteria")

	pdf.SetFont("Helvetica", "", 10)
	startY := pdf.GetY()
	for _, it := range items {
		pdf.Cell(8, 5, "\xe2\x80\xa2")
		pdf.MultiCell(0, 5, it, "", "L", false)
	}
	endY := pdf.GetY()

	pdf.SetDrawColor(14, 116, 144)
	pdf.SetLineWidth(1.0)
	pdf.Line(20, startY-1, 20, endY+2)
	pdf.SetLineWidth(0.2)
	pdf.SetDrawColor(0, 0, 0)
	pdf.Ln(2)
}
