// SPDX-FileCopyrightText: 2026 The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// RenderStakeholderAnalysisPDF is the bespoke renderer for the
// Stakeholder Analysis Document (kind: stakeholder_analysis_doc).
// The companion chart kind (stakeholder_analysis) already has the
// Power × Interest plot; the *document* form is the narrative
// alongside it — per-stakeholder profile cards laying out role,
// power, interest, and the engagement strategy.
//
// Layout:
//
//	Title bar:         Project name + "Stakeholder Analysis"
//	If the doc links to a chart, a one-line "see chart <id>" hint
//	Quadrant legend:   4 chips (Manage Closely / Keep Satisfied /
//	                            Keep Informed / Monitor) with their
//	                            tint colours
//	Stakeholder cards: One bordered card per stakeholder, grouped
//	                   by their engagement quadrant (most-attention
//	                   group first). Each card: name + role +
//	                   power/interest pill + strategy heading +
//	                   wrapped notes.
//	Footer:            generation timestamp
//
// Grouping by quadrant (rather than by name) puts "Manage Closely"
// stakeholders at the top so a reader picks up the doc and
// immediately sees who needs the most attention.
func RenderStakeholderAnalysisPDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("P")
	pdf.SetMargins(20, 18, 20)
	pdf.SetAutoPageBreak(true, 18)
	pdf.SetTitle("Stakeholder Analysis", true)
	pdf.AddPage()

	// Title
	pdf.SetFont("Helvetica", "B", 22)
	pdf.Cell(0, 12, projectName)
	pdf.Ln(13)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "Stakeholder Analysis")
	pdf.Ln(6)
	if ref := getStringSA(content, "matrix_ref"); ref != "" {
		pdf.Cell(0, 5, "Linked chart: "+ref)
		pdf.Ln(5)
	}
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(2)

	drawQuadrantLegend(pdf)
	pdf.Ln(6)

	// Normalise stakeholder rows and bucket by quadrant.
	rows := normaliseStakeholders(getObjectSliceSA(content, "stakeholders"))
	if len(rows) == 0 {
		pdf.SetFont("Helvetica", "I", 10)
		pdf.SetTextColor(120, 120, 120)
		pdf.Cell(0, 6, "No stakeholders recorded.")
		pdf.SetTextColor(0, 0, 0)
	} else {
		buckets := groupByQuadrant(rows)
		for _, q := range quadrantOrder() {
			group := buckets[q.key]
			if len(group) == 0 {
				continue
			}
			drawQuadrantHeader(pdf, q)
			for _, s := range group {
				drawStakeholderCard(pdf, s, q)
			}
			pdf.Ln(2)
		}
	}

	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// stakeholderRow is the typed view of one entry.
type stakeholderRow struct {
	Name     string
	Role     string
	Power    string // "low" | "high"
	Interest string // "low" | "high"
	Strategy string
	Note     string
}

type quadrant struct {
	key      string // "hh" | "hl" | "lh" | "ll"
	title    string // "Manage closely" etc.
	power    string
	interest string
	r, g, b  int
}

// quadrantOrder returns the four quadrants in descending priority,
// matching the chart layout in internal/charts/matrix/stakeholder.go.
func quadrantOrder() []quadrant {
	return []quadrant{
		{"hh", "Manage closely", "high", "high", 127, 29, 29},
		{"hl", "Keep satisfied", "high", "low", 180, 83, 9},
		{"lh", "Keep informed", "low", "high", 14, 116, 144},
		{"ll", "Monitor", "low", "low", 71, 85, 105},
	}
}

func normaliseStakeholders(raw []map[string]interface{}) []stakeholderRow {
	out := make([]stakeholderRow, 0, len(raw))
	for _, r := range raw {
		out = append(out, stakeholderRow{
			Name:     getStringSA(r, "name"),
			Role:     getStringSA(r, "role"),
			Power:    strings.ToLower(getStringSA(r, "power_level")),
			Interest: strings.ToLower(getStringSA(r, "interest_level")),
			Strategy: getStringSA(r, "engagement_strategy"),
			Note:     getStringSA(r, "note"),
		})
	}
	return out
}

func groupByQuadrant(rows []stakeholderRow) map[string][]stakeholderRow {
	buckets := map[string][]stakeholderRow{}
	for _, r := range rows {
		key := quadKey(r.Power, r.Interest)
		buckets[key] = append(buckets[key], r)
	}
	// Stable order within each bucket so the layout is reproducible.
	for k := range buckets {
		sort.SliceStable(buckets[k], func(i, j int) bool {
			return buckets[k][i].Name < buckets[k][j].Name
		})
	}
	return buckets
}

func quadKey(power, interest string) string {
	p := "l"
	if strings.HasPrefix(power, "h") {
		p = "h"
	}
	i := "l"
	if strings.HasPrefix(interest, "h") {
		i = "h"
	}
	return p + i
}

// drawQuadrantLegend renders the 4-strategy reference chips at the
// top of the document.
func drawQuadrantLegend(pdf *gofpdf.Fpdf) {
	pdf.SetFont("Helvetica", "B", 8)
	x := pdf.GetX()
	y := pdf.GetY()
	for _, q := range quadrantOrder() {
		pdf.SetFillColor(q.r, q.g, q.b)
		pdf.SetDrawColor(q.r, q.g, q.b)
		pdf.RoundedRect(x, y, 41, 11, 2, "1234", "F")
		pdf.SetTextColor(255, 255, 255)
		pdf.SetXY(x+2, y+1)
		pdf.CellFormat(38, 4, q.title, "", 0, "L", false, 0, "")
		pdf.SetFont("Helvetica", "", 7)
		pdf.SetXY(x+2, y+5)
		pdf.CellFormat(38, 4, fmt.Sprintf("Power %s · Interest %s", q.power, q.interest), "", 0, "L", false, 0, "")
		pdf.SetFont("Helvetica", "B", 8)
		x += 43
	}
	pdf.SetXY(20, y+12)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
	pdf.SetDrawColor(0, 0, 0)
}

func drawQuadrantHeader(pdf *gofpdf.Fpdf, q quadrant) {
	pdf.Ln(2)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(q.r, q.g, q.b)
	pdf.Cell(0, 7, q.title+" — Power "+q.power+" / Interest "+q.interest)
	pdf.Ln(7)
	pdf.SetTextColor(0, 0, 0)
}

// drawStakeholderCard renders one stakeholder as a bordered card.
// Auto-page-break handles tall cards; the card itself is plain
// rectangles + text so gofpdf wraps cleanly across page boundaries.
func drawStakeholderCard(pdf *gofpdf.Fpdf, s stakeholderRow, q quadrant) {
	x := pdf.GetX()
	y := pdf.GetY()
	const w = 170.0

	// Determine card height based on note length (rough estimate).
	noteLines := 0
	if s.Note != "" {
		// gofpdf wraps at the cell width; 78 chars/line is the
		// typical Helvetica-10 wrap at 165mm body width.
		noteLines = len(s.Note)/78 + 1
	}
	h := 16.0 + float64(noteLines)*4

	pdf.SetFillColor(248, 250, 252)
	pdf.SetDrawColor(q.r, q.g, q.b)
	pdf.RoundedRect(x, y, w, h, 1.5, "1234", "FD")

	// Name (top-left)
	pdf.SetFont("Helvetica", "B", 11)
	pdf.SetTextColor(15, 23, 42)
	pdf.SetXY(x+3, y+1.5)
	pdf.CellFormat(110, 5, s.Name, "", 0, "L", false, 0, "")

	// Power × Interest pill (top-right)
	pdf.SetFont("Helvetica", "B", 7)
	pdf.SetFillColor(q.r, q.g, q.b)
	pdf.SetDrawColor(q.r, q.g, q.b)
	pillX := x + w - 53
	pdf.RoundedRect(pillX, y+1.5, 50, 5, 1, "1234", "F")
	pdf.SetTextColor(255, 255, 255)
	pdf.SetXY(pillX, y+2)
	pdf.CellFormat(50, 4, fmt.Sprintf("P:%s · I:%s", s.Power, s.Interest), "", 0, "C", false, 0, "")

	// Role (left, under name)
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(100, 116, 139)
	pdf.SetXY(x+3, y+6.5)
	pdf.CellFormat(110, 4, s.Role, "", 0, "L", false, 0, "")

	// Strategy (right column, second row)
	strategy := s.Strategy
	if strategy == "" {
		strategy = q.title
	}
	pdf.SetFont("Helvetica", "B", 8)
	pdf.SetTextColor(q.r, q.g, q.b)
	pdf.SetXY(pillX, y+7)
	pdf.CellFormat(50, 4, strategy, "", 0, "C", false, 0, "")

	// Note (full width, third row onward)
	if s.Note != "" {
		pdf.SetFont("Helvetica", "", 9)
		pdf.SetTextColor(40, 40, 40)
		pdf.SetXY(x+3, y+12)
		pdf.MultiCell(w-6, 4, s.Note, "", "L", false)
	}

	pdf.SetXY(x, y+h+1)
	pdf.SetFillColor(255, 255, 255)
	pdf.SetDrawColor(0, 0, 0)
	pdf.SetTextColor(0, 0, 0)
}

// ---- Local helpers ----
func getStringSA(m map[string]interface{}, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}

func getObjectSliceSA(m map[string]interface{}, key string) []map[string]interface{} {
	v, ok := m[key].([]interface{})
	if !ok {
		return nil
	}
	out := make([]map[string]interface{}, 0, len(v))
	for _, x := range v {
		if obj, ok := x.(map[string]interface{}); ok {
			out = append(out, obj)
		}
	}
	return out
}
