// SPDX-FileCopyrightText: 2026 The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// RenderStatementOfWorkPDF is the bespoke renderer for the Statement
// of Work. The SOW is prose-heavy — a formal definition of scope,
// deliverables, timeline, and responsibilities that the parties
// usually sign at the bottom — so the layout follows the Charter
// pattern: portrait A4, section headings + body text + bulleted
// lists, plus a signature block at the end.
//
// Layout:
//
//	Title bar:          Project name (big) + "Statement of Work"
//	Section: Background      (FieldText)
//	Section: Objectives      (StringArr, bulleted)
//	Section: Scope of Work   (FieldText)
//	Section: Deliverables    (StringArr, bulleted)
//	Section: Schedule        (FieldText)
//	Section: Responsibilities (FieldText)
//	Section: Acceptance Criteria (StringArr, bulleted)
//	Sign-off block:    two signature lines
//	Footer:            generation timestamp
//
// Shared helpers from the Charter file (writeSection, writeHeading,
// writeBulletSection) are NOT used here intentionally — each
// bespoke renderer is self-contained per the AGENT.md §10 recipe so
// changing Charter's layout doesn't ripple into every other
// document.
func RenderStatementOfWorkPDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("P")
	pdf.SetMargins(20, 18, 20)
	pdf.SetAutoPageBreak(true, 18)
	pdf.SetTitle("Statement of Work", true)
	pdf.AddPage()

	// Title block
	pdf.SetFont("Helvetica", "B", 22)
	pdf.Cell(0, 12, projectName)
	pdf.Ln(13)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "Statement of Work")
	pdf.Ln(8)
	pdf.SetTextColor(0, 0, 0)

	sowSection(pdf, "Background", getStringSOW(content, "background"))
	sowBullets(pdf, "Objectives", getStringSliceSOW(content, "objectives"))
	sowSection(pdf, "Scope of Work", getStringSOW(content, "scope"))
	sowBullets(pdf, "Deliverables", getStringSliceSOW(content, "deliverables"))
	sowSection(pdf, "Schedule", getStringSOW(content, "schedule"))
	sowSection(pdf, "Responsibilities", getStringSOW(content, "responsibilities"))
	sowBullets(pdf, "Acceptance Criteria", getStringSliceSOW(content, "acceptance_criteria"))

	drawSOWSignOff(pdf)

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

func sowHeading(pdf *gofpdf.Fpdf, text string) {
	pdf.Ln(3)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(0, 80, 130)
	pdf.Cell(0, 7, text)
	pdf.Ln(7)
	pdf.SetTextColor(0, 0, 0)
}

func sowSection(pdf *gofpdf.Fpdf, heading, body string) {
	if body == "" {
		return
	}
	sowHeading(pdf, heading)
	pdf.SetFont("Helvetica", "", 10)
	pdf.MultiCell(0, 5, body, "", "L", false)
	pdf.Ln(2)
}

func sowBullets(pdf *gofpdf.Fpdf, heading string, items []string) {
	if len(items) == 0 {
		return
	}
	sowHeading(pdf, heading)
	pdf.SetFont("Helvetica", "", 10)
	for _, item := range items {
		pdf.Cell(5, 5, "•")
		pdf.MultiCell(0, 5, item, "", "L", false)
	}
	pdf.Ln(2)
}

// drawSOWSignOff renders two signature lines at the bottom of the
// last page. The user fills in names + dates by hand or via the
// digital-signature flow in `internal/crypto`.
func drawSOWSignOff(pdf *gofpdf.Fpdf) {
	pdf.Ln(10)
	pdf.SetFont("Helvetica", "B", 11)
	pdf.SetTextColor(0, 80, 130)
	pdf.Cell(0, 7, "Sign-off")
	pdf.Ln(8)
	pdf.SetTextColor(0, 0, 0)

	// Two side-by-side signature blocks.
	const lineW = 75.0
	xLeft := 20.0
	xRight := 105.0
	y := pdf.GetY()

	pdf.SetFont("Helvetica", "", 9)
	pdf.SetXY(xLeft, y)
	pdf.Cell(lineW, 4, "Authorising party (provider)")
	pdf.SetXY(xRight, y)
	pdf.Cell(lineW, 4, "Authorising party (client)")
	pdf.Ln(8)

	// Underscores for the signature line itself
	pdf.SetDrawColor(100, 100, 100)
	pdf.Line(xLeft, pdf.GetY()+6, xLeft+lineW, pdf.GetY()+6)
	pdf.Line(xRight, pdf.GetY()+6, xRight+lineW, pdf.GetY()+6)
	pdf.Ln(8)

	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.SetXY(xLeft, pdf.GetY())
	pdf.Cell(lineW, 4, "Name / Title / Date")
	pdf.SetXY(xRight, pdf.GetY())
	pdf.Cell(lineW, 4, "Name / Title / Date")
	pdf.SetTextColor(0, 0, 0)
}

// Local string-extraction helpers, kept private to this file so
// rename refactors in one renderer don't surprise others.
func getStringSOW(m map[string]interface{}, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}

func getStringSliceSOW(m map[string]interface{}, key string) []string {
	v, ok := m[key].([]interface{})
	if !ok {
		return nil
	}
	out := make([]string, 0, len(v))
	for _, x := range v {
		if s, ok := x.(string); ok && s != "" {
			out = append(out, s)
		}
	}
	return out
}
