// SPDX-FileCopyrightText: 2026 The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// RenderStatusReportPDF produces a bespoke Status Report PDF — the
// reference implementation for the bespoke-renderer pattern that the
// other 23 generic document kinds can follow as needed.
//
// Layout:
//
//	Page 1:
//	  Big project title (top)
//	  Report date + Overall-status traffic light (green / amber / red)
//	  Schedule + Budget status row (two pill-shaped badges)
//	  Accomplishments      (heading + bulleted list)
//	  In progress          (heading + bulleted list)
//	  Blockers             (heading + red-tinted bulleted list)
//	  Upcoming             (heading + bulleted list)
//	  Footer with nanosecond timestamp + PMForge version
//
// This renderer is what RACI, Risk Register, Project Plan, etc.
// should look like once they get their own bespoke layouts.
//
// Recipe (see AGENT.md §10):
//
//  1. Create internal/documents/<kind>.go with a Render<Kind>PDF
//     func of the same signature.
//  2. Walk content[<key>] explicitly per field — DON'T just defer to
//     renderGenericPDF; the point of a bespoke renderer is layout.
//  3. Add a case in documents.Render() that calls the new function.
func RenderStatusReportPDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("P")
	pdf.SetMargins(20, 18, 20)
	pdf.SetAutoPageBreak(true, 18)
	pdf.SetTitle("Status Report", true)
	pdf.AddPage()

	// Title + project
	pdf.SetFont("Helvetica", "B", 22)
	pdf.Cell(0, 12, projectName)
	pdf.Ln(13)

	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "Status Report")
	pdf.Ln(5)
	if d := getStringS(content, "report_date", ""); d != "" {
		pdf.Cell(0, 6, "Date: "+d)
		pdf.Ln(6)
	}
	pdf.SetTextColor(0, 0, 0)
	pdf.Ln(3)

	// Status badges row
	overall := getStringS(content, "overall_status", "")
	schedule := getStringS(content, "schedule_status", "")
	budget := getStringS(content, "budget_status", "")

	x := 20.0
	y := pdf.GetY()
	drawStatusBadge(pdf, "Overall", overall, x, y)
	drawStatusBadge(pdf, "Schedule", schedule, x+60, y)
	drawStatusBadge(pdf, "Budget", budget, x+120, y)
	pdf.SetXY(20, y+16)
	pdf.Ln(2)

	// Body sections
	writeStatusSection(pdf, "Accomplishments", getStringSliceS(content, "accomplishments"), bulletNormal)
	writeStatusSection(pdf, "In progress", getStringSliceS(content, "in_progress"), bulletNormal)
	writeStatusSection(pdf, "Blockers", getStringSliceS(content, "blockers"), bulletRed)
	writeStatusSection(pdf, "Upcoming", getStringSliceS(content, "upcoming"), bulletNormal)

	// Footer
	pdf.SetY(-20)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// drawStatusBadge renders a pill-shaped status badge. The color comes
// from the value: "green" / "amber" / "red" map directly; anything
// else falls back to slate.
func drawStatusBadge(pdf *gofpdf.Fpdf, label, value string, x, y float64) {
	r, g, b := statusColor(value)
	pdf.SetFillColor(r, g, b)
	pdf.SetDrawColor(r, g, b)
	pdf.RoundedRect(x, y, 50, 12, 3, "1234", "F")
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 8)
	pdf.SetXY(x+3, y+1)
	pdf.CellFormat(44, 4, label, "", 0, "L", false, 0, "")
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetXY(x+3, y+5.5)
	pdf.CellFormat(44, 5, displayStatus(value), "", 0, "L", false, 0, "")
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
	pdf.SetDrawColor(0, 0, 0)
}

func statusColor(v string) (int, int, int) {
	switch v {
	case "green", "Green", "ok", "on_track":
		return 22, 163, 74 // emerald-600
	case "amber", "Amber", "yellow", "at_risk":
		return 217, 119, 6 // amber-600
	case "red", "Red", "blocked":
		return 220, 38, 38 // red-600
	}
	return 100, 116, 139 // slate-500
}

func displayStatus(v string) string {
	if v == "" {
		return "—"
	}
	return v
}

type bulletStyle int

const (
	bulletNormal bulletStyle = iota
	bulletRed
)

func writeStatusSection(pdf *gofpdf.Fpdf, heading string, items []string, style bulletStyle) {
	if len(items) == 0 {
		return
	}
	pdf.Ln(3)
	pdf.SetFont("Helvetica", "B", 12)
	if style == bulletRed {
		pdf.SetTextColor(180, 30, 30)
	} else {
		pdf.SetTextColor(0, 80, 130)
	}
	pdf.Cell(0, 7, heading)
	pdf.Ln(7)
	pdf.SetTextColor(0, 0, 0)

	pdf.SetFont("Helvetica", "", 10)
	for _, item := range items {
		if style == bulletRed {
			pdf.SetTextColor(120, 0, 0)
		}
		pdf.Cell(5, 5, "•")
		pdf.MultiCell(0, 5, item, "", "L", false)
		pdf.SetTextColor(0, 0, 0)
	}
	pdf.Ln(1)
}

// Small typed re-implementations of the generic helpers so this file
// stands alone — the same pattern any future bespoke renderer
// follows. (charter.go has equivalent helpers; future renderers may
// share via internal helpers, but the duplication keeps each
// renderer self-contained for clarity.)
func getStringS(m map[string]interface{}, key, def string) string {
	if v, ok := m[key].(string); ok && v != "" {
		return v
	}
	return def
}

func getStringSliceS(m map[string]interface{}, key string) []string {
	v, ok := m[key].([]interface{})
	if !ok {
		return nil
	}
	out := make([]string, 0, len(v))
	for _, x := range v {
		if s, ok := x.(string); ok {
			out = append(out, s)
		}
	}
	return out
}
