// SPDX-FileCopyrightText: 2026 James L. Burns and The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"sort"
	"time"

	"github.com/jung-kurt/gofpdf"
)

// RenderTeamCharterPDF is the bespoke renderer for the Team Charter.
// The document defines who is on the team, what they do, and how much
// of their capacity is committed. The novel layout element is an
// **inline horizontal allocation bar** in the members table: each
// row's allocation percentage renders both as the number and as a
// proportional filled bar, so a reader scanning the table sees
// staffing distribution at a glance.
//
// Layout:
//
//	Title bar (portrait A4)
//	Section: Team Purpose      (FieldText)
//	Members table:             Name | Role | Allocation | Responsibilities
//	                           (allocation column = % + horizontal bar)
//	Total capacity banner      "Σ allocation: X% (N members)"
//	Section: Ground Rules      (StringArr, bulleted)
//	Footer:                    generation timestamp
func RenderTeamCharterPDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("P")
	pdf.SetMargins(20, 18, 20)
	pdf.SetAutoPageBreak(true, 18)
	pdf.SetTitle("Team Charter", true)
	pdf.AddPage()

	// Title block
	pdf.SetFont("Helvetica", "B", 22)
	pdf.Cell(0, 12, projectName)
	pdf.Ln(13)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "Team Charter")
	pdf.Ln(8)
	pdf.SetTextColor(0, 0, 0)

	tcSection(pdf, "Team Purpose", getString(content, "team_purpose", ""))

	members := normaliseMembers(getObjectSlice(content, "members"))
	if len(members) > 0 {
		// Sort by allocation_pct descending so the most-committed members
		// appear at the top — the reader's first scan answers "who is
		// most invested in this project?"
		sort.SliceStable(members, func(i, j int) bool {
			return members[i].AllocationPct > members[j].AllocationPct
		})

		tcHeading(pdf, "Team Members")
		drawTeamTable(pdf, members)
		drawTeamCapacityBanner(pdf, members)
	}

	tcBullets(pdf, "Ground Rules", getStringSlice(content, "ground_rules"))

	DrawCompactSignatureBox(pdf, projectName, time.Now().Format("2006-01-02"))

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// teamMember is the typed view of one members row.
type teamMember struct {
	Name             string
	Role             string
	Responsibilities string
	AllocationPct    float64
}

func normaliseMembers(raw []map[string]interface{}) []teamMember {
	out := make([]teamMember, 0, len(raw))
	for _, r := range raw {
		out = append(out, teamMember{
			Name:             getStringTC(r, "name"),
			Role:             getStringTC(r, "role"),
			Responsibilities: getStringTC(r, "responsibilities"),
			AllocationPct:    getFloatTC(r, "allocation_pct"),
		})
	}
	return out
}

func tcHeading(pdf *gofpdf.Fpdf, text string) {
	pdf.Ln(3)
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(0, 80, 130)
	pdf.Cell(0, 7, text)
	pdf.Ln(7)
	pdf.SetTextColor(0, 0, 0)
}

func tcSection(pdf *gofpdf.Fpdf, heading, body string) {
	if body == "" {
		return
	}
	tcHeading(pdf, heading)
	pdf.SetFont("Helvetica", "", 10)
	pdf.MultiCell(0, 5, body, "", "L", false)
	pdf.Ln(2)
}

func tcBullets(pdf *gofpdf.Fpdf, heading string, items []string) {
	if len(items) == 0 {
		return
	}
	tcHeading(pdf, heading)
	pdf.SetFont("Helvetica", "", 10)
	for _, it := range items {
		pdf.Cell(5, 5, "\xe2\x80\xa2")
		pdf.MultiCell(0, 5, it, "", "L", false)
	}
	pdf.Ln(2)
}

// drawTeamTable renders the members table with inline allocation bars.
func drawTeamTable(pdf *gofpdf.Fpdf, members []teamMember) {
	cols := []struct {
		header string
		w      float64
		align  string
	}{
		{"Name", 38, "L"},
		{"Role", 35, "L"},
		{"Allocation", 42, "L"},
		{"Responsibilities", 55, "L"},
	}

	// Header
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(30, 41, 59)
	pdf.SetTextColor(241, 245, 249)
	pdf.SetDrawColor(100, 116, 139)
	for _, c := range cols {
		pdf.CellFormat(c.w, 7, c.header, "1", 0, c.align, true, 0, "")
	}
	pdf.Ln(-1)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFont("Helvetica", "", 8)

	rowH := 8.0
	for i, m := range members {
		if i%2 == 0 {
			pdf.SetFillColor(248, 250, 252)
		} else {
			pdf.SetFillColor(255, 255, 255)
		}

		startY := pdf.GetY()

		pdf.CellFormat(cols[0].w, rowH, truncTC(m.Name, 32), "1", 0, "L", true, 0, "")
		pdf.CellFormat(cols[1].w, rowH, truncTC(m.Role, 30), "1", 0, "L", true, 0, "")

		// Allocation cell — draw the border, then overlay the bar.
		allocX := pdf.GetX()
		pdf.CellFormat(cols[2].w, rowH, "", "1", 0, "L", true, 0, "")
		drawAllocationBar(pdf, allocX, startY, cols[2].w, rowH, m.AllocationPct)

		pdf.SetXY(allocX+cols[2].w, startY)
		pdf.CellFormat(cols[3].w, rowH, truncTC(m.Responsibilities, 46), "1", 0, "L", true, 0, "")
		pdf.Ln(-1)
	}
}

// drawAllocationBar draws a horizontal proportional bar inside an
// allocation cell, plus the numeric percentage on the left. Bar
// colour gradates with intensity: 0-25% slate, 26-50% cyan,
// 51-75% amber, 76-100% green (high commitment is good); >100%
// renders in red as an over-allocation warning.
func drawAllocationBar(pdf *gofpdf.Fpdf, x, y, w, h, pct float64) {
	if pct < 0 {
		pct = 0
	}
	r, g, b := allocationColor(pct)

	// Numeric label on the left (always visible regardless of bar fill).
	labelW := 14.0
	pdf.SetXY(x+1, y+1.5)
	pdf.SetFont("Helvetica", "B", 8)
	pdf.SetTextColor(17, 24, 39)
	pdf.CellFormat(labelW, h-3, fmt.Sprintf("%.0f%%", pct), "", 0, "L", false, 0, "")

	// Bar track
	barX := x + labelW + 1
	barY := y + 2.5
	barW := w - labelW - 3
	barH := h - 5
	pdf.SetFillColor(229, 231, 235)
	pdf.Rect(barX, barY, barW, barH, "F")

	// Filled portion — clamp to 100% width, but flag overage in red.
	fill := pct
	if fill > 100 {
		fill = 100
	}
	filledW := barW * fill / 100
	if filledW > 0 {
		pdf.SetFillColor(r, g, b)
		pdf.Rect(barX, barY, filledW, barH, "F")
	}

	// 100% reference tick
	pdf.SetDrawColor(156, 163, 175)
	pdf.SetLineWidth(0.3)
	pdf.Line(barX+barW, barY-0.5, barX+barW, barY+barH+0.5)
	pdf.SetLineWidth(0.2)
	pdf.SetDrawColor(0, 0, 0)
}

// allocationColor maps a percentage to an RGB triple. Used by both
// the inline bar and (potentially) any future capacity heat-map.
func allocationColor(pct float64) (int, int, int) {
	switch {
	case pct > 100:
		return 185, 28, 28 // red: over-allocated
	case pct >= 76:
		return 21, 128, 61 // green: high commitment
	case pct >= 51:
		return 180, 83, 9 // amber
	case pct >= 26:
		return 14, 116, 144 // cyan
	default:
		return 71, 85, 105 // slate: light commitment
	}
}

// drawTeamCapacityBanner sums member allocations and flags
// over-allocation. Useful at a glance: "we have 4 people at 320% =
// 0.8 FTE on average".
func drawTeamCapacityBanner(pdf *gofpdf.Fpdf, members []teamMember) {
	var sum float64
	for _, m := range members {
		sum += m.AllocationPct
	}
	avg := 0.0
	if len(members) > 0 {
		avg = sum / float64(len(members))
	}

	pdf.Ln(2)
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetTextColor(60, 60, 60)
	pdf.Cell(0, 6, fmt.Sprintf("Capacity: %d members  \xc2\xb7  total %.0f%%  \xc2\xb7  avg %.0f%% per member",
		len(members), sum, avg))
	pdf.Ln(7)
	pdf.SetTextColor(0, 0, 0)
}

func getStringTC(m map[string]interface{}, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}

func getFloatTC(m map[string]interface{}, key string) float64 {
	if v, ok := m[key].(float64); ok {
		return v
	}
	return 0
}

func truncTC(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-1] + "\xe2\x80\xa6" // …
}
