// SPDX-FileCopyrightText: 2026 James L. Burns and The PMForge Contributors
// SPDX-License-Identifier: GPL-3.0-or-later

package documents

import (
	"bytes"
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/go-pdf/fpdf"
)

// RenderWBSDocumentPDF is the bespoke renderer for the Work Breakdown
// Structure Document. The novel layout element is an **indented tree**
// rendering driven by the dotted WBS code: an entry with code "1.2.3"
// renders at depth 2 (number of dots), with its parent codes visible
// in the indentation. Each node carries its description and acceptance
// criteria in a bordered card so the reader can read both the
// structure and the contract for that work package.
//
// Layout:
//
//	Title bar (portrait A4)
//	Linked-chart banner: "Linked WBS chart: <chart_id>"
//	Tree of deliverables (sorted by WBS code):
//	  <code chip>  <description>
//	               <acceptance criteria block, indented>
//	Footer: generation timestamp
func RenderWBSDocumentPDF(content map[string]interface{}, projectName string) ([]byte, error) {
	pdf := newDocPDF("P")
	pdf.SetMargins(20, 18, 20)
	pdf.SetAutoPageBreak(true, 18)
	pdf.SetTitle("Work Breakdown Structure", true)
	pdf.AddPage()

	// Title block
	pdf.SetFont("Helvetica", "B", 22)
	pdf.Cell(0, 12, projectName)
	pdf.Ln(13)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(110, 110, 110)
	pdf.Cell(0, 6, "Work Breakdown Structure")
	pdf.Ln(8)
	pdf.SetTextColor(0, 0, 0)

	// Linked chart banner
	if ref := getString(content, "wbs_ref", ""); ref != "" {
		drawWBSChartBanner(pdf, ref)
	}

	deliverables := normaliseDeliverables(getObjectSlice(content, "deliverable_descriptions"))
	if len(deliverables) == 0 {
		pdf.SetFont("Helvetica", "I", 10)
		pdf.SetTextColor(120, 120, 120)
		pdf.Cell(0, 6, "No deliverables documented yet.")
		pdf.SetTextColor(0, 0, 0)
	} else {
		// Sort by WBS code so the tree is in canonical order.
		sort.SliceStable(deliverables, func(i, j int) bool {
			return wbsCodeLess(deliverables[i].Code, deliverables[j].Code)
		})

		pdf.Ln(2)
		for _, d := range deliverables {
			drawWBSNode(pdf, d)
		}
	}

	// Footer
	pdf.SetY(-15)
	pdf.SetFont("Helvetica", "I", 8)
	pdf.SetTextColor(120, 120, 120)
	pdf.CellFormat(0, 5,
		fmt.Sprintf("Generated by PMForge at %s", time.Now().UTC().Format(time.RFC3339Nano)),
		"", 0, "C", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// deliverable is the typed view of one deliverable_descriptions row.
type deliverable struct {
	Code               string
	Description        string
	AcceptanceCriteria string
}

func normaliseDeliverables(raw []map[string]interface{}) []deliverable {
	out := make([]deliverable, 0, len(raw))
	for _, r := range raw {
		out = append(out, deliverable{
			Code:               getStringWBS(r, "wbs_code"),
			Description:        getStringWBS(r, "description"),
			AcceptanceCriteria: getStringWBS(r, "acceptance_criteria"),
		})
	}
	return out
}

// wbsDepth returns the number of dots in a WBS code, treated as the
// node's depth in the tree. "1" → 0, "1.2" → 1, "1.2.3" → 2. Empty
// codes render at depth 0.
func wbsDepth(code string) int {
	if code == "" {
		return 0
	}
	return strings.Count(code, ".")
}

// wbsCodeLess orders WBS codes numerically by segment so that "1.10"
// sorts after "1.9" rather than between "1.1" and "1.2".
func wbsCodeLess(a, b string) bool {
	as := strings.Split(a, ".")
	bs := strings.Split(b, ".")
	n := len(as)
	if len(bs) < n {
		n = len(bs)
	}
	for i := 0; i < n; i++ {
		ai := parseSegment(as[i])
		bi := parseSegment(bs[i])
		if ai != bi {
			return ai < bi
		}
		// Fallback to lexical comparison when both segments parse to
		// the same number (e.g. "1a" vs "1b").
		if as[i] != bs[i] {
			return as[i] < bs[i]
		}
	}
	return len(as) < len(bs)
}

// parseSegment converts a numeric prefix of a WBS segment to int.
// Returns 0 for non-numeric segments so the fallback lexical check in
// wbsCodeLess takes over.
func parseSegment(s string) int {
	n := 0
	for _, ch := range s {
		if ch < '0' || ch > '9' {
			break
		}
		n = n*10 + int(ch-'0')
	}
	return n
}

// drawWBSChartBanner renders a tinted strip linking back to the WBS
// chart whose visual structure this document narrates.
func drawWBSChartBanner(pdf *fpdf.Fpdf, chartRef string) {
	startY := pdf.GetY()
	pdf.SetFillColor(239, 246, 255)
	pdf.SetDrawColor(59, 130, 246)
	pdf.Rect(20, startY, 170, 10, "FD")
	pdf.SetXY(24, startY+1.5)
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetTextColor(30, 58, 138)
	pdf.CellFormat(40, 4, "LINKED WBS CHART", "", 0, "L", false, 0, "")
	pdf.SetXY(24, startY+5.5)
	pdf.SetFont("Helvetica", "", 9)
	pdf.SetTextColor(17, 24, 39)
	pdf.CellFormat(162, 4,
		"Visual structure: "+chartRef+"  (see the chart for the diagram; this doc carries the contract per work package).",
		"", 0, "L", false, 0, "")
	pdf.SetXY(20, startY+12)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetDrawColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
}

// drawWBSNode renders one node in the indented tree. Depth from the
// dotted WBS code drives the left indent; deeper nodes also use a
// softer code-chip colour so the hierarchy is visible without lines.
func drawWBSNode(pdf *fpdf.Fpdf, d deliverable) {
	depth := wbsDepth(d.Code)
	indent := 20.0 + float64(depth)*8 // 8mm per level
	maxWidth := 190.0 - indent

	// Code chip
	chipR, chipG, chipB := wbsChipColor(depth)
	pdf.SetX(indent)
	pdf.SetFont("Helvetica", "B", 9)
	pdf.SetFillColor(chipR, chipG, chipB)
	pdf.SetTextColor(255, 255, 255)
	codeLabel := d.Code
	if codeLabel == "" {
		codeLabel = "—"
	}
	chipW := pdf.GetStringWidth(codeLabel) + 4
	if chipW < 14 {
		chipW = 14
	}
	chipY := pdf.GetY()
	pdf.RoundedRect(indent, chipY, chipW, 5.5, 1.2, "1234", "F")
	pdf.SetXY(indent, chipY+0.8)
	pdf.CellFormat(chipW, 4, codeLabel, "", 0, "C", false, 0, "")

	// Description (right of the chip)
	pdf.SetXY(indent+chipW+3, chipY)
	pdf.SetFont("Helvetica", "B", 10)
	pdf.SetTextColor(17, 24, 39)
	descW := maxWidth - chipW - 3
	if d.Description == "" {
		pdf.SetTextColor(120, 120, 120)
		pdf.CellFormat(descW, 5.5, "(no description)", "", 0, "L", false, 0, "")
	} else {
		pdf.MultiCell(descW, 5, d.Description, "", "L", false)
	}

	// Acceptance criteria — light indent under the description
	if d.AcceptanceCriteria != "" {
		pdf.Ln(1)
		critX := indent + chipW + 3
		pdf.SetX(critX)
		pdf.SetFont("Helvetica", "B", 8)
		pdf.SetTextColor(75, 85, 99)
		pdf.CellFormat(40, 4, "ACCEPTANCE CRITERIA", "", 0, "L", false, 0, "")
		pdf.Ln(4)
		pdf.SetX(critX)
		pdf.SetFont("Helvetica", "", 9)
		pdf.SetTextColor(17, 24, 39)
		pdf.MultiCell(maxWidth-chipW-3, 4.5, d.AcceptanceCriteria, "", "L", false)
	}

	pdf.Ln(2)
	pdf.SetTextColor(0, 0, 0)
	pdf.SetFillColor(255, 255, 255)
}

// wbsChipColor returns a depth-graded fill for the WBS code chip.
// Top-level (depth 0) renders in deep blue; deeper levels fade toward
// slate so the hierarchy is visually distinguishable.
func wbsChipColor(depth int) (int, int, int) {
	switch depth {
	case 0:
		return 30, 58, 138 // blue-900
	case 1:
		return 59, 130, 246 // blue-500
	case 2:
		return 14, 116, 144 // cyan-700
	case 3:
		return 100, 116, 139 // slate-500
	default:
		return 148, 163, 184 // slate-400
	}
}

func getStringWBS(m map[string]interface{}, key string) string {
	if v, ok := m[key].(string); ok {
		return v
	}
	return ""
}
